### ISSUE TITLE
Build fails with visual studio

### ISSUE THREAD

**Issue by jhtrauntvein** [cmake-js/cmake-js#105]
Using the "Visual Studio 15 2017 Win64 Generator", I am getting a consistent build failure when trying to compile my add-on.  This seems to be caused by the project name getting plugged into the "AdditionalOptions" compiler directive.  When this happens, the CL compiler appears to want to interpret the project name as one of the source files and, since there is no such source file, an error is emitted instead.  I can clear the error by removing the project name from this option in the generated project file but this does no good since this will get overwritten the next time that the project structure changes.  My CMakeLists.txt file is attached.

[CMakeLists.txt](https://github.com/cmake-js/cmake-js/files/1584292/CMakeLists.txt)

**Comment by Julusian** [comment]
I dont fully follow the description of this without a log to look at, but given the age and lack of additional comments I shall assume it was either fixed or the author has moved on
