### ISSUE TITLE
Custom Configuration Types

### ISSUE THREAD

**Issue by computerquip-streamlabs** [cmake-js/cmake-js#108]
I'd like to be able to use configurations outside of Release and Debug. Currently, I'm having to force the Release configuration to the default RelWithDebInfo flags so I can obtain PDBs but it seems kinda redundant when I could normally just build the RelWithDebInfo config type.

**Comment by twoi** [comment]
I was just looking for the same. I can build the RelWithDebInfo configuration from VisualStudio, but I'd like to be able to do it using cmake-js

**Comment by d3x0r** [comment]
This seems to be working worse than it used to; I cannot seem to get cmake-js to make a RelWithDebInfo output... it always does `cmake --build (full path to build/) --config [Release/Debug]`

**Comment by Julusian** [comment]
This has been implemented in #251 https://github.com/cmake-js/cmake-js/blob/master/README.md?plain=1#L45-L46
