### ISSUE TITLE
Cannot publish or pull prebuilt binaries

### ISSUE THREAD

**Issue by heaths** [cmake-js/cmake-js#114]
From looking through documentation and seeing how issue #97 was handled (seems the guy went off and created a project but has not been active), it seems using prebuilt modules a la node-pre-gyp is not currently supported.

Is publishing and pulling prebuilt binaries on the radar?

**Comment by VictorLeach96** [comment]
I've submitted a PR to prebuild to implement this.
https://github.com/prebuild/prebuild/pull/214
