### ISSUE TITLE
Support for node.js versions less than 4.5

### ISSUE THREAD

**Issue by buntarb** [cmake-js/cmake-js#124]
Hey. Seems like starting from version 3.5.0 you are broke support for node.js version less than 4.5. 
Log of error:

`/var/www/sphere/kududb/node_modules/cmake-js/node_modules/tar/lib/pack.js:32`
`const EOF = Buffer.alloc(1024)`
`                   ^`
`TypeError: Buffer.alloc is not a function`

Buffer.alloc was added in 4.5 as I know. I think this should be highlighted in the documentation.

**Comment by unbornchikken** [comment]
I consider it as a bug, because that was unwanted. I'm gonna try to patch Buffer's prototype to have that method and hope that tar doesn't use anything more from new apis.

**Comment by unbornchikken** [comment]
I have to leave this, since many modules that I use dropped support of the old runtimes. I have to update modules regularly because of security reports. That was the reason of tar update though. I'll update the documentation about this.
