### ISSUE TITLE
Parallel build

### ISSUE THREAD

**Issue by axkibe** [cmake-js/cmake-js#129]
Is there a way to make this work so it compiles multiple files at once?
Similar than it would when running cmake directly.

```./node_modules/cmake-js/bin/cmake-js build -m -- -j 4```

I'm currently updating node-vtk which uses cmake-js and it are a lot wrappers to be compiled...

**Comment by wzhouwzhou** [comment]
+1 on this, any feedback and/or documentation and updates on this question would be great!

**Comment by unbornchikken** [comment]
It is already supported by CMake, and CMake.js doesn't hide or override this feature anyhow.

https://stackoverflow.com/questions/10688549/how-to-configure-portable-parallel-builds-in-cmake

**Comment by wzhouwzhou** [comment]
Okay, thanks for clarifying!

**Comment by andreyryabov** [comment]
Could you please provide an example of a command that launches a parallel build

`cmake-js build -m -- -j 4 `

does not work for me.

**Comment by claudv** [comment]
First of all, thanks for providing this really useful package. 
Unfortunately I am having the same problem, the option does not seem to work. Could it be confirmed that @axkibe command is correct and should definitely work?

**Comment by unbornchikken** [comment]
`CMAKE_BUILD_PARALLEL_LEVEL=4 cmaje-js build`
