### ISSUE TITLE
cmake-js disables all compiler warnings on OSX

### ISSUE THREAD

**Issue by corystegel** [cmake-js/cmake-js#132]
`cmake-js` unconditionally disables all compiler warnings on OSX by [adding "-w" to the C++ compiler flags on OSX](https://github.com/cmake-js/cmake-js/blob/master/lib/es6/toolset.js#L130). 

This should not be done because forcing **all** projects on OSX to hide **all** their compiler warnings is a very bad idea. Warnings should be controlled by the underlying `CMakeLists.txt`, not `cmake-js`.

**Comment by unbornchikken** [comment]
There was a reason for this option, but I cannot remember exactly. I believe this originated from the corresponding node-gyp defaults. Anyway that would be a breaking change for already existing modules, they should add -w to their CMakeLists.txt once it get landed. Let me think about it.

**Comment by corystegel** [comment]
To avoid breaking existing modules that have `-Werror` in their cmake perhaps add an option to `cmake-js` to disable all warnings which defaults to true? This would allow projects on OSX to enable warnings which isn't possible right now.

If "-w" is removed and a project is not escalating warnings to errors then all this will do is cause extra warning output to print to the console when the module is compiling which shouldn't break anything. It also lets developers know that areas of their code need attention.

If "-w" is removed and a project **is** escalating warnings to errors they are probably wrongly assuming that they have no warnings. This would cause these existing modules to break if they actually did have warnings that were previously being hidden.

**Comment by unbornchikken** [comment]
Fixed as of v4.0.0, see changelog.
