### ISSUE TITLE
How can I rebuild the supplied node.lib

### ISSUE THREAD

**Issue by JungleCatSW** [cmake-js/cmake-js#134]
I need to build the node.lib and export all the symbols, as I use OpenSSL in my code and with node.lib doesn't have all the symbols. 

How can I build a custom copy of the node.lib ?

**Comment by RSATom** [comment]
Better address this question to Node.js developers.

**Comment by Julusian** [comment]
That is not relevant to this project. the node.lib is part of the nodejs runtime and not something we built.
I think #128 is a better representation of this issue
