### ISSUE TITLE
Lodash old library dependence 

### ISSUE THREAD

**Issue by BarushevEA** [cmake-js/cmake-js#135]
![image](https://user-images.githubusercontent.com/29018530/44395277-1693a700-a542-11e8-8eac-feac50261e6f.png)
![image](https://user-images.githubusercontent.com/29018530/44395318-31feb200-a542-11e8-95d4-a0ec0bc6e581.png)
Good afternoon!
Help please solve the problem.
Description of the problem:
https://www.npmjs.com/advisories/577

**Comment by Julusian** [comment]
This was updated a few releases ago
