### ISSUE TITLE
npm audit warning

### ISSUE THREAD

**Issue by dmooney65** [cmake-js/cmake-js#140]
Hi,

Any chance of updating your `lodash` dependency to get rid of the annoying `npm audit` error?

Patched in  >=4.17.5
Dependency of cmake-js
Path  cmake-js > lodash
More info https://nodesecurity.io/advisories/577

Thanks

**Comment by unbornchikken** [comment]
Fixed as of v4.0.0.

**Comment by dmooney65** [comment]
Excellent thanks!
