### ISSUE TITLE
building nwjs addon using cmake-js

### ISSUE THREAD

**Issue by GeorgeGuZ** [cmake-js/cmake-js#143]
Hello,
First of all, thank you very much for making this great tool that make my work much more efficient.

When I am building c++ addon for nwjs, I setup the package.json file according to my environment as follow:
{
...
  "cmake-js": {
    "runtime": "nw",
    "runtimeVersion": "0.33.4",
    "arch": "x64"
  }
...
}

Then I use the "cmake-js --out path/to/build/directory". After that the compile process great and smooth. Then I require the .node file, and run my project. It return me the following result:
------------------------------------------------------------------------------------------------
**internal/modules/cjs/loader.js:731
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^**

Error: The specified module could not be found.
\\?\F:\repo\sip-ua\modules\sip-ua\modules\sip-ua\Release\sip_ua.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (F:\repo\sip-ua\app.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
-------------------------------------------------------------------------------------------------------
Do anyone know what happen here? Thanks a lot

**Comment by RSATom** [comment]
Are you sure use x64 NW.js?
Are you sure all dependency .dll are accessible directly or via PATH?

**Comment by RSATom** [comment]
The second is most possible reason I think.

**Comment by GeorgeGuZ** [comment]
@RSATom Thank you for your response. If I use the following configuration for package.json it works fine:
{
...
  "cmake-js": {
    "arch": "x64"
  }
...
}
Only when I specify "runtime" as "nw" it shows the error. So I think if some .dll is not accessible it should not work in normal build as well.

**Comment by RSATom** [comment]
again, 
> Are you sure use x64 NW.js?

I mean you have to use  x64 `NW.js` runtime to be able use x64 .node addon. 

> If I use the following configuration for package.json it works fine:

When you don't specify `runtime` at all it builds addon for `node.js`  I think. So, you try it with node or still with `NW.js`?

**Comment by RSATom** [comment]
To find out if it missing some dll, you could try http://www.dependencywalker.com/

**Comment by unbornchikken** [comment]
I consider it as resolved, but feel free to open up if you need further assistance.
