### ISSUE TITLE
EINVALIDTAGNAME with custom CMake options

### ISSUE THREAD

**Issue by BotellaA** [cmake-js/cmake-js#149]
I am trying to give a custom CMake option using the npm command `npm install -- --CDMyCustomLib_DIR:PATH=directory`
```
{
  "scripts": {
    "install": "cmake-js compile"
  },
  ...
}
```
I got this error:
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "--CDMyCustomLib_DIR:PATH=directory": Tags may not have any characters that encodeURIComponent encodes.
```

Any idea how to solve this?
Thanks for your help!

**Comment by unbornchikken** [comment]
As far as I know npm install does not support extending install script's argument list by "--".

**Comment by BotellaA** [comment]
How would you pass custom arguments using npm? We can only call cmake-js directly?

**Comment by RSATom** [comment]
I've used environment variables and cmake-js package directly:
https://github.com/RSATom/WebChimera.js/blob/master/rebuild.js
https://github.com/RSATom/WebChimera.js/blob/master/package.json#L23
https://github.com/RSATom/WebChimera.js/blob/master/build_electron.cmd

**Comment by BotellaA** [comment]
> As far I know yes, you should. But you can use environment variables or npm config values to configure you build process. https://github.com/cmake-js/cmake-js#npm-config-integration

Why the variables are all uppercased? For example, the CMake find_package command may need the variable `<package>_DIR` where `<package>` is case sensitive.

**Comment by unbornchikken** [comment]
Because on the time of development CMake was case insensitive. It would be a breaking change to address it. It might worth the effort and a semver major release, but you should open up an issue about it, when we can discuss more.
