### ISSUE TITLE
NPM Config Integration with case sensitive CMake variable

### ISSUE THREAD

**Issue by BotellaA** [cmake-js/cmake-js#150]
The current NPM Config Integration implementation transforms the given variable into its uppercased equivalent. However, CMake is now (since at least version 3.0) case sensitive and can handle case sensitive variables.

For example, the CMake find_package command may need the variable <package>_DIR where <package> is case sensitive. Giving the uppercased version will not work.

**Comment by unbornchikken** [comment]
I can imagine this in a semver major update.

**Comment by BotellaA** [comment]
Is it something you plan on doing? I am more a C++ dev but maybe I can help.

**Comment by unbornchikken** [comment]
A PR would be greatly appreciated.

**Comment by BotellaA** [comment]
Fixed by #151
