### ISSUE TITLE
electron v4 `win_delay_load_hook` support suggestions

### ISSUE THREAD

**Issue by xVanTuring** [cmake-js/cmake-js#153]
> On Windows, by default, node-gyp links native modules against node.dll. However, in Electron 4.x and higher, the symbols needed by native modules are exported by electron.exe, and there is no node.dll in Electron 4.x. In order to load native modules on Windows, node-gyp installs a delay-load hook that triggers when the native module is loaded, and redirects the node.dll reference to use the loading executable instead of looking for node.dll in the library search path (which would turn up nothing). As such, on Electron 4.x and higher, 'win_delay_load_hook': 'true' is required to load native modules.

[a-note-about-win_delay_load_hook](https://electronjs.org/docs/tutorial/using-native-node-modules#a-note-about-win_delay_load_hook)

I am using cmake-js to build electron native addon,works fine on v3,but v4 (windows) has a new feature that currently cmake-js is not supported, called `win_delay_load_hook`.
After digging into node-gyp, I find it's actually quite simple. The key is  containing a `win_delay_load_hook.cc` file
``` c++
/*
 * When this file is linked to a DLL, it sets up a delay-load hook that
 * intervenes when the DLL is trying to load 'node.exe' or 'iojs.exe'
 * dynamically. Instead of trying to locate the .exe file it'll just return
 * a handle to the process image.
 *
 * This allows compiled addons to work when node.exe or iojs.exe is renamed.
 */

#ifdef _MSC_VER

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include <windows.h>

#include <delayimp.h>
#include <string.h>

static FARPROC WINAPI load_exe_hook(unsigned int event, DelayLoadInfo* info) {
  HMODULE m;
  if (event != dliNotePreLoadLibrary)
    return NULL;

  if (_stricmp(info->szDll, "iojs.exe") != 0 &&
      _stricmp(info->szDll, "node.exe") != 0)
    return NULL;

  m = GetModuleHandle(NULL);
  return (FARPROC) m;
}

decltype(__pfnDliNotifyHook2) __pfnDliNotifyHook2 = load_exe_hook;

#endif

```
and set /DELAYLOAD to target,like following
``` cmake
set(list_of_dlls "io.exe" "node.exe" "%(DelayLoadDLLs)")
foreach(dll_name ${list_of_dlls})
   set(space_separated_list "${space_separated_list} /DELAYLOAD:${dll_name}")
endforeach()
set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "${space_separated_list}")
```
then everything works fine!
![tim 20190116202325](https://user-images.githubusercontent.com/11146248/51248937-abed7700-19cc-11e9-8703-9d54fac821b2.png)

**BUT** I don't know how to change the cmake-js to make it work automaticly, and i only know little cmake command.

So hope you guys can make it work!😋

**Comment by unbornchikken** [comment]
I aware of this. Because CMake have enough features that make adding delay load hook support easy (like you've already did it), and CMake.js doesn't hide or overlay those, I decided to not hack it automatically in for every module. If someone needs that, it just a few lines of CMakeLists.txt away.

**Comment by xVanTuring** [comment]
I actually figure it out. cmake-js can only provide the file for convience, and set a variable like WIN_DELAY_LOAD_HOOK for win env, the rest can be document in README.

**Comment by Minami-Kotori** [comment]
Hi there, I'm still having troubles getting it to work with electron on windows, is there a specific order for the set_target_properties? According to Electron documentation, 

> you link against node.lib from Electron and not Node. If you link against the wrong node.lib you will get load-time errors when you require the module in Electron.

I'm a bit confused as I'm new to native modules, any help would be mostly appreciated. Thanks

**Comment by xVanTuring** [comment]
@Minami-Kotori , Sorry I can't help you right now, 'cause I'm using linux, you can take a look at my project [cquant](https://github.com/xVanTuring/cquant) for more detail

**Comment by Minami-Kotori** [comment]
> @Minami-Kotori , Sorry I can't help you right now, 'cause I'm using linux, you can take a look at my project [cquant](https://github.com/xVanTuring/cquant) for more detail

The cmakelist in your project saved the day! Cheers
