### ISSUE TITLE
Generator parsing is broken with CMake 3.14.0-rc1

### ISSUE THREAD

**Issue by gjasny** [cmake-js/cmake-js#158]
This is a heads-up issue that CMake generator parsing is broken with CMake 3.14: https://gitlab.kitware.com/cmake/cmake/issues/18906

It is easily solve-able on CMake.js side by adding:
```
if (_.startswith(gen, "*")) {
  gen = gen.substr(1).trim();
}
```
 But maybe the cmake devs roll back that change to not force all users to upgrade CMake.js.

**Comment by unbornchikken** [comment]
Thanks for the info. Should I make an update right now, or should I wait for the release version? What do you think?

**Comment by gjasny** [comment]
It does not look like CMake will change the behavior. The following code seems to parse the generators from the `capabilities` command. Could you please push it into shape? If you want me to test it I'd need a 3.6 backport branch.

```diff
--- a/lib/es6/cMake.js
+++ b/lib/es6/cMake.js
@@ -66,10 +66,21 @@ CMake.isAvailable = function (options) {
 };
 
 CMake.getGenerators = async(function* (options) {
-    let arch = " [arch]";
     options = options || {};
     let gens = [];
     if (CMake.isAvailable(options)) {
+        // try parsing machine-readable capabilities
+        try {
+            let stdout = yield processHelpers.exec((options.cmakePath || "cmake") + " -E capabilities");
+            let capabilities = JSON.parse(stdout);
+            gens = capabilities.generators.map(x => x.name);
+            return;
+        } catch (error) {
+            console.log(error);
+        }
+
+        // fall back to parsing help text
+        let arch = " [arch]";
```

**Comment by gjasny** [comment]
In the meantime I updated our repo to cmake-js v5. Is there anything I could help with?

**Comment by gjasny** [comment]
@payload Would you be able to polish the draft above and bring it to merge quality?

**Comment by unbornchikken** [comment]
A PR would be greatly appreciated, coz I'm a bit tight on schedule as always. Thanks.

**Comment by unbornchikken** [comment]
https://github.com/cmake-js/cmake-js/releases/tag/v5.1.0
