### ISSUE TITLE
64-Bit NODE.EXE linked in all builds with electron 5.0.0-beta.5

### ISSUE THREAD

**Issue by PaulFreund** [cmake-js/cmake-js#163]
First off, thank you very much for this useful project! For cross platform with a Raspberry Pi I needed to update from cmake-js 4.0.1 to 5.1.0 and from electron 3.0.3 to 5.0.0-beta.5 which worked like a charm on RPi and Ubuntu. 

Now when I compile on Windows with VS2017 I first have to patch #160 and then my .node file links against NODE.EXE which most likely is no problem with normal node processes but it is with electron. Now I can more or less work around it like described in this comment https://github.com/nodejs/node-addon-api/issues/269#issuecomment-455580129 but I don't think it is a nice solution and it does not work properly for ia32 arch because the DLL still tries to load a 64-Bit NODE.EXE

**Comment by PaulFreund** [comment]
Just realized this is because of the node.lib we are linking against from the official electron mirror, we can keep this ticket open for tracking but can not do anything about it in cmake-js

**Comment by unbornchikken** [comment]
Please try with v5.2.0 and let me know the result.

**Comment by unbornchikken** [comment]
Please test with 5.2.2+

**Comment by unbornchikken** [comment]
I mean 5.3.2

**Comment by Julusian** [comment]
It sounds like this was fixed in the releases menioned above
