### ISSUE TITLE
ERR! OMG There is no Visual C++ compiler installed. Install Visual C++ Build Toolset or Visual Studio.

### ISSUE THREAD

**Issue by burakkp** [cmake-js/cmake-js#168]
Hi Everyone,

I run cmake on npm but I get a this error(below). I have installed Visual Studio 2019 Community Edition. 

How can I figure out this error?

![cmake_Error](https://user-images.githubusercontent.com/5391838/55946144-6f888a80-5c4c-11e9-9c2f-9bebf0942ea4.png)

**Comment by unbornchikken** [comment]
Have you installed Visual C++ part of Visual Studio too?

**Comment by burakkp** [comment]
Yes, I think! I installed those's. Can you look below?


![cmake_Error1](https://user-images.githubusercontent.com/5391838/55947711-4ae1e200-5c4f-11e9-8193-49e74df098b8.png)

**Comment by unbornchikken** [comment]
What is the ouput of **cmake-js <your-options> --log-level=silly** ?

**Comment by burakkp** [comment]
> What is the ouput of **cmake-js --log-level=silly** ?

Sorry for late answer.

I get that error.

![cmake_Error2](https://user-images.githubusercontent.com/5391838/56135564-5277f280-5f91-11e9-8014-b6e64c3ff865.png)

**Comment by unbornchikken** [comment]
You haven't included the end of the log.

**Comment by burakkp** [comment]
> You haven't included the end of the log.

Sorry, I added now all screen view.

![cmake_Error2_AllView](https://user-images.githubusercontent.com/5391838/56142918-cb7e4680-5f9f-11e9-945c-1bf671e956fb.png)
![cmake_Error2_AllView_Continue](https://user-images.githubusercontent.com/5391838/56143010-02545c80-5fa0-11e9-8aee-fc0f4c3882dd.png)

**Comment by unbornchikken** [comment]
What's the output of ```cmake -E capabilities```?

**Comment by burakkp** [comment]
> What's the output of `cmake -E capabilities`?

![cmake_Error3](https://user-images.githubusercontent.com/5391838/56191852-74bf4e00-602d-11e9-94ef-a9d81d73f144.png)

**Comment by raghavdwivediIntero** [comment]
@unbornchikken
Hi, I am also facing the Same error with cmake-js when I have visual studio 2019 installed.
But when I use cmake-gui I am able to configure and generate.

**Comment by unbornchikken** [comment]
Please help me by testing PR #178 at your side.

**Comment by raghavdwivediIntero** [comment]
> Please help me by testing PR #178 at your side.

We are still facing the same issue. 

PS C:\NO-BACKUP\Code\RnD\new\> cmake-js
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\raghav.dwivedi\\AppData\\Roaming\\npm\\node_modules\\cmake-js\\bin\\cmake-js' ]
ERR! OMG There is no Visual C++ compiler installed. Install Visual C++ Build Toolset or Visual Studio.
ERR! OMG There is no Visual C++ compiler installed. Install Visual C++ Build Toolset or Visual Studio.

**Comment by unbornchikken** [comment]
> > What's the output of `cmake -E capabilities`?
> 
> ![cmake_Error3](https://user-images.githubusercontent.com/5391838/56191852-74bf4e00-602d-11e9-94ef-a9d81d73f144.png)

I can't see VS 2019 listed there. Are you using the latest version of CMake?

**Comment by raghavdwivediIntero** [comment]
`{"generators":[{"extraGenerators":["CodeBlocks","CodeLite","Sublime Text 2","Kate","Eclipse CDT4"],"name":"MinGW Makefiles","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Visual Studio 12 2013 ARM","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 14 2015 ARM","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 16 2019","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 15 2017 Win64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 15 2017","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 15 2017 ARM","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 14 2015 Win64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 12 2013","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 12 2013 Win64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 14 2015","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 11 2012","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 11 2012 ARM","platformSupport":true,"toolsetSupport":true},{"extraGenerators":["CodeBlocks","CodeLite","Sublime Text 2","Kate","Eclipse CDT4"],"name":"Unix Makefiles","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Visual Studio 11 2012 Win64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 10 2010 Win64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 10 2010","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 10 2010 IA64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 9 2008","platformSupport":true,"toolsetSupport":false},{"extraGenerators":[],"name":"Visual Studio 9 2008 Win64","platformSupport":true,"toolsetSupport":false},{"extraGenerators":["CodeBlocks"],"name":"NMake Makefiles JOM","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Visual Studio 9 2008 IA64","platformSupport":true,"toolsetSupport":false},{"extraGenerators":[],"name":"MSYS Makefiles","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Borland Makefiles","platformSupport":false,"toolsetSupport":false},{"extraGenerators":["CodeBlocks","CodeLite","Sublime Text 2","Kate","Eclipse CDT4"],"name":"NMake Makefiles","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Green Hills MULTI","platformSupport":true,"toolsetSupport":true},{"extraGenerators":["CodeBlocks","CodeLite","Sublime Text 2","Kate","Eclipse CDT4"],"name":"Ninja","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Watcom WMake","platformSupport":false,"toolsetSupport":false}],"serverMode":true,"version":{"isDirty":false,"major":3,"minor":14,"patch":1,"string":"3.14.1","suffix":""}}`

**Comment by raghavdwivediIntero** [comment]
I am using following version for cmake

![image](https://user-images.githubusercontent.com/49674585/58690235-57e69c00-8389-11e9-8def-9fbfc50b3d78.png)

**Comment by TomzBench** [comment]
+1 I get this issue. I work around it by adding --msvs_version=2015 to my install command. For some reason when I use 2019 compiler it finds the C compiler but not the CXX compiler...

**Comment by Shilpa-shreebe1997** [comment]
even i am facing the same problem.

**Comment by Kreijstal** [comment]
It'd be nice if cmake.js installed a c compiler if none was installed (yeah, I know) but otherwise it will just get more and more people complaining, just google "node-gyp error" and see how many man hours have been lost due to this issue, and the issues of node-gyp is pretty much the same, "wtf, why error?" 
If you don't, prepare to teach 11 yo kids how to install compilers.

**Comment by lufang2000** [comment]
I had the same issue on Windows and found the solution here https://gauriatiq.medium.com/c-native-addon-independent-of-node-js-version-using-napi-node-addon-api-and-cmake-53315582cbd1. Thanks Atiq Gauri!

The key is install Node using GUI installer, from nodejs.org, not using nvm. During the installation, check the checkbox to install Tools for Native Modules.

**Comment by fanfare** [comment]
tried to figure out this situation for a couple of hours with no luck. i tried the above steps but it still wasnt working out. i tried something else and it ended up working. if you are using cygwin, and have installed cmake with the cygwin package manager, open the cygwin package manager and uninstall cmake. then install cmake using the msi installer on the cmake website. this worked for me.

recap: `node.js` installed via the gui installer (not `nvm`), `cmake` is installed via the installer on the cmake website, the visual studio installer has `VC++ 2017 version 15.9 v14.16 latest v141 tools` installed

**Comment by Julusian** [comment]
The recommended way to get the correct compiler is to select that checkbox when installing nodejs.
Or if you are not using the installer, you should be able to install the [Chocolatey package manager](https://chocolatey.org/install), and run `choco install visualstudio2017-workload-vctools` in an Administrator Powershell

From reading this thread it looks like everyone was having an issue with lacking the tools or correct cmake version. If anyone thinks they still have a bug then please open a new issue and I can investigate

**Comment by ArchismanKarmakar** [comment]
@Julusian @unbornchikken @burakkp @Kreijstal @lufang2000 

Still facing the issue. Installing VS Tools from chocolatey is not a solution. I have tried with VS tools 2022, 2019, 2017, and even installing it from chocolatey but no luck yet. It keeps showing the same issue. Linux has no such issues, but it is not a solution.

Kindly reopen this issue and let us contribute here.

**Comment by Kreijstal** [comment]
> @Julusian @unbornchikken @burakkp @Kreijstal @lufang2000
> 
> Still facing the issue. Installing VS Tools from chocolatey is not a solution. I have tried with VS tools 2022, 2019, 2017, and even installing it from chocolatey but no luck yet. It keeps showing the same issue. Linux has no such issues, but it is not a solution.
> 
> Kindly reopen this issue and let us contribute here.
> 
> ![image](https://private-user-images.githubusercontent.com/92569441/311482225-441ed02b-7ea9-420f-afa5-be8bb68560ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjE1NTMsIm5iZiI6MTcxMDA2MTI1MywicGF0aCI6Ii85MjU2OTQ0MS8zMTE0ODIyMjUtNDQxZWQwMmItN2VhOS00MjBmLWFmYTUtYmU4YmI2ODU2MGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA5MDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZjg1NjdiMjkxY2ZlZmVjZDI4OWJmYzZjODM3ODM5YWRmYjFjMDlkMmIxODRlNWI1NjAxYjg2MTQzZGM2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DxLVnJJeTIcvRCVH0th8oUjgOakVZcMAUVhDZFLL4WM)
> 
> ![image](https://private-user-images.githubusercontent.com/92569441/311492235-b06cbb51-badd-4799-9625-25735525b733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjE1NTMsIm5iZiI6MTcxMDA2MTI1MywicGF0aCI6Ii85MjU2OTQ0MS8zMTE0OTIyMzUtYjA2Y2JiNTEtYmFkZC00Nzk5LTk2MjUtMjU3MzU1MjViNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA5MDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZDhlZjQxYTBkNjNlMmZmMTg4ZjY4ZDFiOWZjMzVhNjZhNDI4NDM5NWY5ZDEwMzllNGYzMDM3NDk5NWQ3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1GFXTkQqQfCm_Uc2Fbsh2hg6w5C0U7fIXFUdmeI9FZ8)

ahh I wonder if node-gyp could support msys2 then we wouldn't need all of this crap

**Comment by sec-henning** [comment]
We had the same issue after installing visual Studio after the Build Tools had been installer previously....

First the issue was the the determination of the available VS Versions failed as the following skript was missing
https://github.com/microsoft/vssetup.powershell

After the installation, the issue remained that the software searched in the first installed BuildTools (old) for the new Generator in the old path

The workaround was to specify the environmental Variable explicitly by:
$env:npm_config_msvs_version=2019 

using command of cmake-js explicitly the usage of the generator option solved the issue :)
cmake-js build -G "Visual Studio 16 Win64" -D

**Comment by sec-henning** [comment]
> using command of cmake-js explicitly the usage of the generator option solved the issue :) cmake-js build -G "Visual Studio 16 Win64" -D

Today it required the usage of -G "Visual Studio 16 2019" following a complete clean and trying to rebuild
