### ISSUE TITLE
cmake-js support for Visual Studio 2019

### ISSUE THREAD

**Issue by ViliusSutkus** [cmake-js/cmake-js#172]
Step 1: Install VS 2019.
Step 2: Find VS 2019 in cmake -E capabilities.
Step 3: cmake-js picks VS 2017 Win64 as preferred generator.

Is there anything specific that's needed to be implemented to make VS 2019 work with cmake-js out of the box?

**Comment by unbornchikken** [comment]
5.2.2 should handle VS 2019 correctly.
