### ISSUE TITLE
flags.make:10: *** missing separator when adding library with add_subdirectory

### ISSUE THREAD

**Issue by Superlokkus** [cmake-js/cmake-js#175]
I successfully created a native node addon with napi and cmakejs. But when adding a simple library the unix make file, generated by cmake-js explodes with

> [ 50%] Linking CXX static library liblib_name.a
> [ 50%] Built target lib_name
> CMakeFiles/spielwiese.dir/flags.make:10: *** missing separator.  Stop.
> make[1]: *** [CMakeFiles/Makefile2:72: CMakeFiles/spielwiese.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ERR! OMG Process terminated: 2

Minimized example project: https://github.com/Superlokkus/spielwiese/tree/napi

The root CMakeLists should be close or intented to be close to cmakejs example boilerplate version, just with an additional function `PARSE_CMAKEJS_PROPERTIES`  to also build it via a cmake CLI command, for nice developing with IDEs like CLion. However the problem persisits when removing the `PARSE_CMAKEJS_PROPERTIES` function.

I added the library with a `add_subdirectory`, if you remove https://github.com/Superlokkus/spielwiese/blob/napi/CMakeLists.txt#L47 aka `add_subdirectory(src/lib_name)` and change https://github.com/Superlokkus/spielwiese/blob/napi/CMakeLists.txt#L63 aka `target_link_libraries(${PROJECT_NAME} PUBLIC ${CMAKE_JS_LIB} lib_name)` to `target_link_libraries(${PROJECT_NAME} PUBLIC ${CMAKE_JS_LIB})` and also remove 
https://github.com/Superlokkus/spielwiese/blob/napi/src/spielwiese.cpp#L3 aka `#include <lib_name/lib_name.hpp>`,

the project builds again incl. the mocha test. However add the example library and you get the error again.

**Comment by Superlokkus** [comment]
For reputation gain and better google search coverage I also created a SO question: https://stackoverflow.com/questions/56288848/unix-make-file-fails-with-cmakejs-when-adding-a-dependency

**Comment by Superlokkus** [comment]
I did some experimentation and it seems 

```
target_include_directories(${PROJECT_NAME}
        PUBLIC
        $<INSTALL_INTERFACE:include>
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
        PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}/src
        )
```

is doing the trouble, so it looks like cmakejs has some problem with that command?!

**Comment by Superlokkus** [comment]
the generated make file has a new line in its `CXX_INCLUDES` for some reason, is the include flag handling wrong ?
```
CXX_INCLUDES = -I/home/markus/.cmake-js/node-x64/v11.15.0/include/node -I/home/markus/CLionProjects/spielwiese/node_modules/node-addon-api
 -I/home/markus/CLionProjects/spielwiese/src/lib_name/include 
```

**Comment by Superlokkus** [comment]
Truns out 

```
execute_process(COMMAND node -p "require('node-addon-api').include"
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE NODE_ADDON_API_DIR 
```
because the output of node.js it contains a new line, expect a PR to correct your documentation

**Comment by Pospelove** [comment]
I had the same problem. Thank you for saving my time.
