### ISSUE TITLE
5.3.1 breaks MSVC electron builds

### ISSUE THREAD

**Issue by Superlokkus** [cmake-js/cmake-js#188]
Build of native node modules for electron with cmake-js version 5.2.0 worked both on linux/gcc and windows/msvc, but breaks at least since 5.3.1. with linker errors about node symbols for windows/MSVC. Linux/gcc still works.

See as https://github.com/Superlokkus/electron-native-node-demo/tree/ok builds as it should (checkout and yarn install with Visual Studio 15 2017 / MSVC 14

while  https://github.com/Superlokkus/electron-native-node-demo/tree/fail does not

while the only difference between both branches is the difference in the cmake-js version (see yarn.lock).

Error log snippets, full version attached, with cmake-js 5.3.1:

> marku@DESKTOP-GAAF53B MINGW64 ~/Documents/electron-native-node-demo (fail)
> $ yarn install
> yarn install v1.16.0
> error C:\Users\marku\Documents\electron-native-node-demo\node_modules\spielwiese: Command failed.
> Exit code: 1
> Command: cmake-js compile
> Arguments:
> Directory: C:\Users\marku\Documents\electron-native-node-demo\node_modules\spielwiese
> Output:
> [ 'C:\\Program Files\\nodejs\\node.exe',
>   'C:\\Users\\marku\\Documents\\electron-native-node-demo\\node_modules\\cmake-js\\bin\\cmake-js',
>   'compile' ]
> info TOOL Using Visual Studio 15 2017 generator.
> info CMD CONFIGURE
> info RUN cmake "C:\Users\marku\Documents\electron-native-node-demo\node_modules\spielwiese" --no-warn-unused-cli -G"Visual Studio 15 2017" -DCMAKE_JS_VERSION="5.3.1" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="C:\Users\marku\Documents\electron-native-node-demo\node_modules\spielwiese\build" -DCMAKE_JS_INC="C:\Users\marku\.cmake-js\electron-x64\v3.1.9\src;C:\Users\marku\.cmake-js\electron-x64\v3.1.9\deps\v8\include;C:\Users\marku\.cmake-js\electron-x64\v3.1.9\deps\uv\include" -DCMAKE_JS_SRC="C:/Users/marku/Documents/electron-native-node-demo/node_modules/cmake-js/lib/cpp/win_delay_load_hook.cc" -DNODE_RUNTIME="electron" -DNODE_RUNTIMEVERSION="3.1.9" -DNODE_ARCH="x64" -DCMAKE_JS_LIB="C:\Users\marku\.cmake-js\electron-x64\v3.1.9\x64\node.lib" -DCMAKE_SHARED_LINKER_FLAGS="/DELAYLOAD:NODE.EXE"

> spielwiese.obj : error LNK2019: unresolved external symbol _napi_create_string_utf8 referenced in function "class Napi::Object __cdecl Init(class Napi::Env,class Napi::Object)" (?Init@@YA?AVObject@Napi@@VEnv@2@V12@@Z) [C:\Users\marku\Documents\electron-native-node-demo\node_modules\spielwiese\build\spielwiese.vcxproj]

> C:\Users\marku\Documents\electron-native-node-demo\node_modules\spielwiese\build\Release\spielwiese.node : fatal error LNK1120: 25 unresolved externals [C:\Users\marku\Documents\electron-native-node-demo\node_modules\spielwiese\build\spielwiese.vcxproj]
> ERR! OMG Process terminated: 1
[errorlog.txt](https://github.com/cmake-js/cmake-js/files/3446063/errorlog.txt)

**Comment by unbornchikken** [comment]
It doesn't look right: `C:\Users\marku.cmake-js\electron-x64\v3.1.9\x64\node.lib`
That should be `C:\Users\marku\.cmake-js\electron-x64\v3.1.9\x64\node.lib`

Could you link the --log-level=verbose versions of all build, please?

**Comment by Superlokkus** [comment]
> It doesn't look right: `C:\Users\marku.cmake-js\electron-x64\v3.1.9\x64\node.lib`
> That should be `C:\Users\marku\.cmake-js\electron-x64\v3.1.9\x64\node.lib`
> 
> Could you link the --log-level=verbose versions of all build, please?

How do I get cmake-js to pass that flag to cmake?

**Comment by unbornchikken** [comment]
It the module's directory just enter: `node \node_modules\cmake-js\bin\cmake-js compile --log-level=verbose`

**Comment by Superlokkus** [comment]
I assume you meant after a failed  `yarn install` since otherwise no `node_modules`
The output:

[errorlog.txt](https://github.com/cmake-js/cmake-js/files/3446425/errorlog.txt)

**Comment by unbornchikken** [comment]
Sorry, I meant that I'd like to see the output of the compilation of the electron native module only that causes yarn install to fail.

**Comment by Superlokkus** [comment]
> Sorry, I meant that I'd like to see the output of the compilation of the electron native module only that causes yarn install to fail.

No problem:
[log.txt](https://github.com/cmake-js/cmake-js/files/3446497/log.txt)

**Comment by unbornchikken** [comment]
I can only see a logs of a successful compilation in that.

**Comment by Superlokkus** [comment]
Thats right, the node modul still compiles fine with vanilla nodejs, but fails when used for an electron runtime project.

**Comment by Superlokkus** [comment]
> I can only see a logs of a successful compilation in that.

But I guess you wanted to see build of the native module alone already as electron module. I modified it as standalone electron module, but I looks to me it's pretty much the same as when using integrated as a dep in the electron app:
[errorlog.txt](https://github.com/cmake-js/cmake-js/files/3446774/errorlog.txt)

https://github.com/Superlokkus/spielwiese/tree/napi_for_electron_fail_demo

**Comment by unbornchikken** [comment]
I can see:

```
C:\Users\marku\.cmake-js\electron-x64\v3.1.9\x64\node.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86' [C:\Users\marku\Documents\spielwiese\build\spielwiese.vcxproj]
```
You should add:

"arch": "ia32"

To CMake.js section in package.json.

**Comment by Superlokkus** [comment]
Sticking the architecture in the package json of course makes the maintance of native node modules harder, since in general it should be portable code running everywhere.

**Comment by unbornchikken** [comment]
It is impossible because npm builds the module, and node runs the npm, and CMake.js runs inside that node process the has nothing to do with the target platform or runtime. But modules should not have anything CMake.js related in their package.json. That should be declared in the (root) application's package.json file.

https://github.com/cmake-js/cmake-js#runtimes

Check the important section.

**Comment by Superlokkus** [comment]
So then you should add to your documentation that the architecture property is required for electron run times from now on.

Still makes the root application inflexible, since one might want to build an electron app for windows x86 and windows arm. 

And the fact that your old version just works fine, suggests you were able to proper detect it but lost that ability in the new version. (although there exists a slim chance that it just works because of some weird side effect to be fair)

**Comment by unbornchikken** [comment]
Since you should bundle your application for each platforms, it is an acceptable solution. Way much better than node-gyp, where you gotta build you native module one-by-one by hand, right? I still don't think that is a regression error. I think the second build uses artefacts of the first one, that's why it gets failed. Unfortunately I cannot test it right now. Just for the record, would you please try it with arch defined?

**Comment by Superlokkus** [comment]
It works with arch defined (sorry I didn't mentioned it already).
But it is definitely a regression, since it works out of the box with the other branch. Which has no node modules or any build artifacts at all. And I always deleted anything between me build attempts, with `git clean -fxd`.

**Comment by Superlokkus** [comment]
Note: It explodes when using `"arch":  "x64"`

**Comment by unbornchikken** [comment]
Please test **master**.

**Comment by Superlokkus** [comment]
> Please test **master**.

Yarn install with master fails:

```
uccess Saved lockfile.
$ cmake-js compile
/home/markus/development/spielwiese/node_modules/cmake-js/lib/es6/toolset.js:206
        if (ver === vswhereVersion || yield vsDetect.isInstalled(ver + ".0")) {
                                      ^^^^^

SyntaxError: Unexpected strict mode reserved word
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/markus/development/spielwiese/node_modules/cmake-js/lib/es6/cMake.js:17:15)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/markus/development/spielwiese/node_modules/cmake-js/lib/es6/buildSystem.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/markus/development/spielwiese/node_modules/cmake-js/lib/es6/index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by unbornchikken** [comment]
Sorry I had uncommited changes. Please test now.

**Comment by Superlokkus** [comment]
Now it seems to work, even without the damn arch specification in neither the root nor the module package.json. To be specific: Now it seems to stop working in the windows git bash because of visual studio version finding snafu, but now the visual studio command shells with the paths set to a specific arch are working again. 

But give me some time to test it on all my configuration and making sure I did not change something accidentially.

**Comment by unbornchikken** [comment]
Let me know. I'm gonna tag a release if it finally solves this fucked up Visual Studio situation. I hate 'em.

**Comment by Superlokkus** [comment]
Damn I had a bad yarn.lock with the cmakejs in 5.2.0.:
Actually now I have the same behavior with the git bash and the VS prompt, that cmake-js is to eater to choose the not installed but installed before Visual Studio 2019 generator rather than the cmake default VS2017 (even in the 2017 command prompt) .

So I will install VS2019 again, but if you could meanwhile tell me how to tell cmake-js which generator to use for native module dependencies, it would help too.

And regarding MSVC: I feel ya.

**Comment by unbornchikken** [comment]
> eater to choose the not installed but installed before Visual Studio 2019 generator rather than the cmake default VS2017

That;s vswhere.

> if you could meanwhile tell me how to tell cmake-js which generator to use for native module dependencies, it would help too.

https://github.com/cmake-js/cmake-js#npm-config-integration

Check the UPDATE section.

**Comment by Superlokkus** [comment]
Thanks for the tips.
It works now for my minimal project, and I assume it will also for my production project, for which I first have to rebuild boost. That takes some time, I will reopen the issue in the case it surprisingly won't work there.

Thank you very much!

**Comment by unbornchikken** [comment]
Cool. Released as of v5.2.2.

**Comment by unbornchikken** [comment]
I mean 5.3.2

**Comment by Superlokkus** [comment]
After the whole VS2019 installation and boost shebang was over, it turned out, altough yarn seemed to build everything, the DLL initialization routine in my productive electron app thrown an error. 

The used native module alone worked as a nodejs module consumed by its unit/module test. I will add code in my minimized example, that acutally tries to use the the minimized module as an electron app.

**Comment by Superlokkus** [comment]
Alright, after fighting with weird yarn lock behavior (I guess the windows file api gives yarn old .lock files some seconds after a git checkout) I got some good and bad findings:

Old electron 3 and cmakejs 5.2:  https://github.com/Superlokkus/electron-native-node-demo/tree/actual_napi_use Compiles and works

Old electron 3 and new cmake js 5.3. https://github.com/Superlokkus/electron-native-node-demo/tree/actual_napi_use_with_update Compiles and works

New electron 6 and old cmakejs 5.2: https://github.com/Superlokkus/electron-native-node-demo/tree/actual_napi_use_with_electron_update Compiles but runtime error

New electron 6 and new cmakejs 5.3.: https://github.com/Superlokkus/electron-native-node-demo/tree/atucal_napi_use_with_cmakejs_and_electron_update Compiles but runtime error

Runtime error: 

> Uncaught Error: A dynamic link library (DLL) initialization routine failed.
> \\?\C:\Users\marku\AppData\Local\Programs\electron_native_node_demo\resources\app.asar.unpacked\node_modules\spielwiese\build\Release\spielwiese.node
>     at process.func (electron/js2c/asar.js:155)
>     at process.func [as dlopen] (electron/js2c/asar.js:155)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:828)
>     at Object.func (electron/js2c/asar.js:155)
>     at Object.func [as .node] (electron/js2c/asar.js:164)
>     at Module.load (internal/modules/cjs/loader.js:645)
>     at Function.Module._load (internal/modules/cjs/loader.js:560)
>     at Module.require (internal/modules/cjs/loader.js:685)
>     at require (internal/modules/cjs/helpers.js:16)
>     at index.html:10 

So it looks like we had a MSVC version finding problem, but by reinstalling the newest MSVC is compiled again, but meanwhile we have an electron problem. So I bother them.

So thanks, looks like you are in the clear

**Comment by Superlokkus** [comment]
Opend https://github.com/electron/electron/issues/19884
