### ISSUE TITLE
Would it be better to use N-API instead of NAN?

### ISSUE THREAD

**Issue by paulocoghi** [cmake-js/cmake-js#193]
I saw the wiki [Tutorial 01](https://github.com/cmake-js/cmake-js/wiki/TUTORIAL-01-Creating-a-native-module-by-using-CMake.js-and-NAN) explaining how to use CMake-JS and NAN, but I would like to know if using N-API instead of NAN would be a better/updated approach.

Thanks!

**Comment by Julusian** [comment]
Yes, Node-API should be prefered over NAN when possible.
Node-API is designed to be a stable api that works across node versions, unlike NAN which needs a different build for each major node and electron version, and frequently has breaking api changes.

The tutorials are rather outdated and could do with updating
