### ISSUE TITLE
Is it possible to use C libraries inside NodeJS through cmake-js?

### ISSUE THREAD

**Issue by paulocoghi** [cmake-js/cmake-js#194]
I am trying to learn what option would be the best to use a C library inside of NodeJS.

I am a little [confused](https://stackoverflow.com/questions/58187323/nodejs-difference-between-n-api-nan-node-gyp-and-cmake-js) about the different options and approaches, but it is clear to me that cmake-js is better than node-gyp.

But can I use cmake-js (with N-API or NAN) to use a C library inside NodeJS, or it is designed to work only with C++ libraries?

Thanks!

**Comment by unbornchikken** [comment]
It's for C++, but you can use compiled C libraries with CMake. CMake.js basically support anything that CMake itself provides.

**Comment by paulocoghi** [comment]
Ok! Thanks!
