### ISSUE TITLE
Not able to find node.lib in windows on compiling with minGW

### ISSUE THREAD

**Issue by santhiya-v** [cmake-js/cmake-js#195]
I m writting a simple N-API module and compiling using cmake-js with generator "MinGW Makefiles".  While building, I am facing error when its linking the library. 

```-- Build files have been written to: E:/cosmos/examples/mingw_test/build
[ 33%] Linking CXX shared library mingw_test.node
g++.exe: error: /DELAYLOAD:NODE.EXE: No such file or directory
g++.exe: error: C:Usersjanakg.cmake-jsnode-x64v12.11.1win-x64node.lib: No such file or directory
```
node.lib is in the directory C:\Users\janakg\.cmake-js\node-x64\v12.11.1\win-x64\node.lib but its searching for node.lib in C:Usersjanakg.cmake-jsnode-x64v12.11.1win-x64node.lib where slashes are missing. I tried setting CMAKE_JS_INC and CMAKE_JS_LIB path in my CMakeLists.txt but CMake-js does not pick my location from there. My code can be found here [https://github.com/santhiya-v/N-API_CPP](url)

**Comment by unbornchikken** [comment]
MinGW is not supported, and I have no plans to make it. However a PR would be greatly appreciated.

**Comment by santhiya-v** [comment]
Thank you for your quick response.

Would you guess anything from the error message ? If you give few points on
this context, it will be helpful to do PR.
