### ISSUE TITLE
INFO: Building context-aware plugins

### ISSUE THREAD

**Issue by d3x0r** [cmake-js/cmake-js#199]
Node-gyp defines a variable 'NODE_GYP_MODULE_NAME' which is based on package.json { name: }.

It would be nice if cmake-js could auto-magically also define this variable.
node.h requires it to use [NODE_MODULE_INIT](https://nodejs.org/docs/latest-v10.x/api/addons.html#addons_context_aware_addons)

Yes, this can be defined in a project's CMakeLists.txt.

**Comment by ExE-Boss** [comment]
The variable you’re looking for is `CMAKE_PROJECT_NAME`, which is set to what’s passed to the **CMake** `project(…)` function in `CMakeLists.txt`.

**Comment by Julusian** [comment]
Im not sure if we should automatically set a node_gyp variable. It wouldnt surprise me if something somewhere uses this variable to check for node-gyp vs other build systems. Not sure how that would work, but im sure someone will find a way.

For node-api based modules, the recommended init way is https://github.com/nodejs/node-addon-examples/blob/7ca7b6d03c1acb72fe292b4be468009534a20ff3/1_hello_world/node-addon-api/hello.cc#L14
It looks like nan provides an equivalent wrapper.

Or you can set the variable yourself in the cmake file.
