### ISSUE TITLE
Fresh install warns of deprecations: request (entirely) and mkdirp < 1.x

### ISSUE THREAD

**Issue by codingthat** [cmake-js/cmake-js#209]
``` sh
yarn add cmake-js
```

```
warning cmake-js > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning cmake-js > tar > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning cmake-js > unzipper > fstream > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```

**Comment by codingthat** [comment]
Request alternatives: https://github.com/request/request/issues/3143

**Comment by codingthat** [comment]
The `tar` dependency is in the midst of solving their `mkdirp` dependency: https://github.com/npm/node-tar/issues/248

Latest `fstream` uses a newer `mkdirp`, it but `unzipper` doesn't seem to use that in the version used by `cmake-js`.

**Comment by Julusian** [comment]
Dependencies have been updated in dab3f728eebe9d1a0bdbb7675af3d4967caf57c5, so either these will go away in the next release or are dependent on work being done inside those depenedencies
