### ISSUE TITLE
 Native addon built using cmake-js crashes when c++ std::filesystem used in an electron.js app

### ISSUE THREAD

**Issue by AtiqGauri** [cmake-js/cmake-js#210]
### Expected Behavior
my native addon perfectly works as standalone (include c++17 std::filesystem) and it should do the same when called in electron app

### Actual Behavior
When I import addon into electron app everything works fine until the statement of std:filesystem.function() arrives. After which electron gets crashed ( Blank white screen) with developer tools option disconnected.

### Additional Info
Same module works perfectly if we run it as standalone node app

### To Reproduce
https://github.com/AtiqGauri/Electron-CPP17-filesytem-native-addon

**Comment by bromix** [comment]
Which system? Windows? If so, can you take a look at this [Windows (Visual Studio) use Multi-threaded Debug/Release](https://github.com/cmake-js/cmake-js/issues/208)
Is's a problem I encountered while using c++17 under windows and the only solution is to link multithreaded.

**Comment by Julusian** [comment]
The solution here is to build your module as /MT instead of /MD.

In v7.0.0 this is recommended in the docs and the release notes for upgrading existing projects.
