### ISSUE TITLE
Invalid command line switch for "cmd.exe" System.argumentException: Item has already been added. (PATH vs Path)

### ISSUE THREAD

**Issue by TomzBench** [cmake-js/cmake-js#232]
Hello,

When building my package with Git Bash shell I receive the following error:

```bash
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB6001: Invalid command line switch for "cmd.exe". System.ArgumentException: Item has already been added. Key in dictionary: 'Path'  Key being added: 'PATH' [C:\${snip}\build\ZERO_CHECK.vcxproj]
```

I think this issue is very closely related to this issue: https://github.com/dotnet/msbuild/issues/5726

The problem is not clear how to fix, though MSBUILD suggests that this is a "wontfix" and that I should work around the issue. But it's not clear what to add to my cmake-js usage to work around this issue. It's seems the workaround is required in cmake-js?

**Comment by gentunian** [comment]
@TomzBench did you find a workaround for this?

**Comment by gentunian** [comment]
I tracked the issue down to https://github.com/nodejs/node/pull/35210 so if this could be backported to older versions of nodejs then this issue I think will disappear.

**Comment by gentunian** [comment]
Going through the code it looks like in master this was addressed:

https://github.com/cmake-js/cmake-js/blob/e311b71564be3925f35f0861f85817a823d4cff0/lib/processHelpers.js#L12

**Comment by gentunian** [comment]
Until a new release is out, I'm using the change from that commit as well:
```
 "cmake-js": "github:cmake-js/cmake-js#e311b71564be3925f35f0861f85817a823d4cff0",
```

**Comment by unbornchikken** [comment]
ixed as of 6.2.1

**Comment by gentunian** [comment]
@unbornchikken I tested 6.2.1 and that fix does not solve the issue, it continues there. I added the line from my [PR](https://github.com/cmake-js/cmake-js/pull/243), and that effictively solves the issue:

```javascript
if (process.platform === "win32" && process.env.Path !== undefined && process.env.PATH !== undefined) {
   const PATH = process.env.Path;
   delete process.env.PATH;
   process.env.Path = PATH;
}
```

**Comment by gentunian** [comment]
to clarify even more...
![image](https://user-images.githubusercontent.com/1090113/129630803-ada465b2-a6d0-4085-a497-710d406bc960.png)
I did that directly to the source in the "node_modules" folder.

**Comment by gentunian** [comment]
@unbornchikken current condition won't work because:

```javascript
if (env.Path && en.PATH && env.Path !== env.PATH)
```
won't be true when `env.Path === env.PATH` and you won't delete any. You will still have 2 environament variables, one for `Path` and other for `PATH`.

this line:
 ```javascript
env.PATH = `$env.Path};${env.PATH}`;
``` 
should be in a different inner condition.
