### ISSUE TITLE
cmake-js "finds" non-existing compiler

### ISSUE THREAD

**Issue by kenr** [cmake-js/cmake-js#242]
If a user has uninstalled VS 2019 the registry key Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\Microsoft.VisualStudio.MinShell.Interop.Msi,v16 is still there.

The _isVSvNextInstalled then returns true, but the compiler is not installed.
https://github.com/cmake-js/cmake-js/blob/18f4cbec2f955deea0e18588c9ce9b0aac03a576/lib/vsDetect.js#L78

I do not understand why _isVSvNextInstalled is required when vswhere should cover it...

Output from my system that previously had VS2019 installed, now uninstalled:
```
Not searching for unused variables given on the command line.
CMake Error at CMakeLists.txt:9 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.
```

**Comment by Julusian** [comment]
I expect this to be resolved in the upcoming 7.0.0 release.
We are using the same version selection logic as node-gyp, so it should be a lot more robust and not hit this issue
