### ISSUE TITLE
Request for new patch release that includes the migration from Request to Axios

### ISSUE THREAD

**Issue by bretambrose** [cmake-js/cmake-js#247]
The PR here  -- https://github.com/cmake-js/cmake-js/pull/233 -- migrated cmake-js from using the deprecated request package to axios.  As a downstream consumer (https://github.com/awslabs/aws-crt-nodejs) of cmake-js, we are starting to get pressure to get request out of our dependency set.  Given the criticality of cmake-js to our build and fallback install process, the only way we can get rid of request is if cmake-js gets an updated publish.

**Comment by unbornchikken** [comment]
It's done. There was many issues after merging the last couple of PRs, and I don't have much time for this project anymore. If you wanna help, I can provide contributor rights for this repo and the npm registry too.

**Comment by bretambrose** [comment]
Thanks for doing this.  Kind of a bummer to hear about your time situation, but I definitely understand.  That being said, I know virtually nothing about Javascript and so would be a bad choice of maintainer even with sufficient free time =/
