### ISSUE TITLE
v6.2.0 registry key query failures on Windows (vsDetect.js)

### ISSUE THREAD

**Issue by bretambrose** [cmake-js/cmake-js#249]
Hello,

After updating to 6.2.0, we are running into some issues with the toolchain detection on Windows.  In particular, this PR (https://github.com/cmake-js/cmake-js/pull/227), reworked vsDetect.js to use processHelpers.execFile() instead of .exec(), but those registry checks are now failing where they used to succeed.  The problem appears to be the escaped quotes at the start and end of the key path.  Perhaps the new api call (execFile) essentially quotes each of the elements of the argument list?

We have a CD machine with only old versions of Visual Studio on it, so no vswhere to shortcircuit the installation path check.  I added some logging to toolset.js and vsDetect.js and ran bin/cmake-js on that machine.  Here's some relevant output:

```
verb TOOL Looking for vswhere.exe at 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'.
verb TOOL Could not find vswhere.exe (VS installation is probably older than 15.2).
...
verb TOOL Considering generator Visual Studio 14 2015 Win64
verb TOOL Checking generator Visual Studio 14 2015 Win64 for installation location.
verb VSDetect Exception:  Command failed: reg query HKLM\Software\Microsoft\VisualStudio\14.0
verb VSDetect Exception:  ERROR: The system was unable to find the specified registry key or value.
```

However, from the same vs command prompt I can run:

```
C:\temp\aws-crt-nodejs>reg query "HKLM\Software\Microsoft\VisualStudio\14.0"
```

and get:

```
HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\AD7Metrics
HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\CLSID
HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\Debugger
HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\Setup
HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\VC
HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\VSPerf
```

Finally, if I remove the escaped quotation marks from the key argument, _isVSInstalled() successfully queries the registry keys and configuration succeeds.

I don't know if removing the escaped quotes on the key argument is the right fix.  It seems odd that this was refactored as part of the space-in-path PR when there's no spaces in the registry key path and it seems unlikely that Microsoft would add spaces to the version number.

**Comment by unbornchikken** [comment]
Please open up a PR with your changes, and I will verify.
