### ISSUE TITLE
Cannot open include file: 'v8config.h': No such file or directory

### ISSUE THREAD

**Issue by Chase-William** [cmake-js/cmake-js#253]
First off, this is a small issue, but I think it is worth mentioning for anyone who comes across it. 

## Problem

If you are compiling specifically for `electron v13.1.17` you may run into an issue as follows:
`C:\Users\my_name_here\.cmake-js\electron-x64\v13.1.7\include\node\cppgc/common.h(9,10): fatal error C1083: Cannot open include file: 'v8config.h': No such file or directory [D:\Dev\my_project_name\build\addon.vcxproj]`

I am using `cmake-js v6.2.1` and my `package.json` for `cmake-js` looks as follows:
```json
"cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "13.1.7",
    "arch": "x64"
  }
```
If we go to the file and the specified line we find: 
```cpp
// TODO(chromium:1056170): Remove dependency on v8.
#include "v8config.h"  // NOLINT(build/include_directory)
```

## Work-Around

I tested compiling for a few different versions of electron and I found that versions below and above `electron v13.1.7` compiled successfully. **You just need to avoid `v13.1.7`.**

My project has a lot going on so I haven't tested `ia32` and other architectures because my dependencies are not configured for them. Further, because of this it could just be an issue with my setup but it seemed too specific to be just that, hence my posting here. Any-who, I hope this is helpful to anyone who stumbles across this until gets fixed (again not a huge issue).

-- Let me know if more info is needed!

**Comment by Julusian** [comment]
Thanks for the detailed write up.
Is this still a problem in later releases of electron?
Is this when using nan or node-api?

**Comment by Chase-William** [comment]
I am not sure as I swapped over to just using node-gyp instead and haven't had any issues there. According to my commits I was using `node-addon-api` at that time.

**Comment by Julusian** [comment]
OK. Re-reading it, it does sound like an issue with that specific version. As it is no longer in support, it is unlikely to be hit by anyone else
