### ISSUE TITLE
Feature request: possibility to work completely offline

### ISSUE THREAD

**Issue by alejandroclaro** [cmake-js/cmake-js#254]
I have a project where the build must be performed completely offline and only audited components can be used during the build. We have been developing some native NodeJS modules, and we are trying to use CMake instead of node-gyp. However, looks like that if "cmake-js compile" is executed during the "install" script, it always tries to download the runtime instead of looking for common places where it could be already located.

It should be possible to control the dependencies that cmake-js is using without unexpected surprises.

**Comment by milahu** [comment]
offline build is also needed for nixos

https://github.com/cmake-js/cmake-js/blob/18f4cbec2f955deea0e18588c9ce9b0aac03a576/lib/dist.js#L102-L106

the files in [dist.downloaded](https://github.com/cmake-js/cmake-js/blob/18f4cbec2f955deea0e18588c9ce9b0aac03a576/lib/dist.js#L45-L83) (`deps/v8/include/v8.h` ...) are part of the nodejs source at https://github.com/nodejs/node (version must match the node binary, of course)

so the hardest part is getting the [dist.internalPath](https://github.com/cmake-js/cmake-js/blob/18f4cbec2f955deea0e18588c9ce9b0aac03a576/lib/dist.js#L31-L39)

**Comment by alejandroclaro** [comment]
Why not considered the definition of npm_config_nodedir variable that is use in other build systems like node-gyp and electron-gyp?

They allow the definition of this variable thought `npm config set` and use the path instead or trying to download the runtime headers if this is defined.

**Comment by alejandroclaro** [comment]
It solves the issue.
