### ISSUE TITLE
Additional maintainers

### ISSUE THREAD

**Issue by Julusian** [cmake-js/cmake-js#274]
I am relying on this library for a package I maintain https://www.npmjs.com/package/@julusian/jpeg-turbo. Every now and then I consider replacing cmake with node-gyp to go with the better supported approach, until I remember that the library I am wrapping has such a complex cmake script it will be hard to recreate.

I am a little saddened to see how little maintenance is happening to this project, and the number of decent looking prs growing along with stale or outdated issues piling up.
@unbornchikken Would you be interested in some help maintaining this, and modernising the code? A bunch of the dependencies are really outdated, and some are easily replaced with builtin equivalents in recent node versions (eg bluebird)

**Comment by unbornchikken** [comment]
Yeah, IRL issues and other interests are really preventing me to focus on this unfortunately. I can provide you contributor status if you're interested.

**Comment by Julusian** [comment]
I can appreciate that, it happens to us all
Yeah I am happy to help out with as much as you are comfortable with :)

The main things I would like to do here (in order):
1) Drop support for iojs, that is long past being useful
1) Drop some unnecessary dependencies (unzipper, bluebird, maybe lodash?)
2) Update some outdated dependencies (depending on what feels safe/not too much risk)
3) Triage all the open issues. Various ones are already fixed, or have been answered. And a bunch are very stale and look specific to eol versions of node/electron
4) Triage the open prs, and merge any which look useful
5) Depending on how long it took to get this far, look at at fixing any bugs that remain

**Comment by unbornchikken** [comment]
Would you tell your npm username? I'm gonna give maintainer access there to you too.

**Comment by Julusian** [comment]
Thanks its also [julusian](https://www.npmjs.com/~julusian)

If you are happy with this idea, I am good to drop node 10 and 12 support and make the next release be v7.0.0.
There is no need to drop node 12 support yet, but as it was EOL a couple of weeks ago, it saves doing any semver major release when it does become a problem.

**Comment by unbornchikken** [comment]
Yeah that would be fine. I've just added you as maintainer on npm too.
