### ISSUE TITLE
Language in doc

### ISSUE THREAD

**Issue by rleddy** [cmake-js/cmake-js#277]
I am deciding to use this for my C++ builds under node.js. But, I am a little embarrassed by the idea of telling people to adopt this tool or that I will since there is something similar to profanity in the doc.

This does seem to be the only answer to gyp, which I gather is not really favored for support by some organizations. I started looking into a Lua solution as well. But, there is work to be done there.  Using cmake makes sense.

So, while I may seem to be uncool, I do think it's a point worth making. And, I think changing  a word or two will help with marketability.

**Comment by Julusian** [comment]
I have replaced everything I could see, let me know if there are any other words that I didnt spot.

> This does seem to be the only answer to gyp, which I gather is not really favored for support by some organizations.

Including the nodejs tsc themselves. They are considering replacing gyp with something else, but have yet to decide what that should be.  I cant find the link Im thinking of, but there is an initiative https://github.com/nodejs/build-toolchain-next
