### ISSUE TITLE
move from rc to run-con

### ISSUE THREAD

**Issue by goatandsheep** [cmake-js/cmake-js#282]
The most popular fork of rc is currently [run-con](https://www.npmjs.com/package/run-con) which is being maintained whereas rc has been deprecated. Should we move to run-con?

**Comment by Julusian** [comment]
I don't see any compelling reason to move currently. All you have changed so far is updating dependencies within their semver ranges (which doesnt need an update of rc).

Once there are some functional changes that fix issues reported by users (I am not aware of any such issues currently) or some needed out of semver range dependency update then I shall reconsider
