### ISSUE TITLE
Snyk ReDoS issue in ansi-regex nested dependency

### ISSUE THREAD

**Issue by Pradeep976** [cmake-js/cmake-js#292]
Describe the bug
My Snyk Dashboard shows that this package has a high level security issue in one of the packages that is installed by the dependencies of this package,

The problem is with the package ansi-regex@2.1.1 which causes Regular Expression Denial of Service ( REDOS ), this issue in fixed in the package ansi-regex 3.0.1

![image](https://user-images.githubusercontent.com/61454285/208856897-beca6add-1981-418a-84e7-6bbc59eea289.png)

Can you please make use of the latest packages in order to solve this issue

Expected Behavior
No issues in Snyk

Current Behavior
1 High issue reported in snyk

Reproduction Steps
When running our external Snyk pipeline this issue is reported in the Snyk dashboard

Possible Solution
No response

Additional Information/Context
No response

Version used
^6.3.0

Environment details (OS name and version, etc.)
Mac OS Monterey 12.4

**Comment by Julusian** [comment]
This is not an issue in the 7.x releases.
Fixing in 6.x requires updating `yargs` from 3.x to 13.x. That is quite a version jump, with a long list of breaking changes, that I don't feel I can sufficiently test to ensure nothing will break with the time I have available.
