### ISSUE TITLE
ERR! find VS  (os: win11 vs: Visual Studio 2022 Community)

### ISSUE THREAD

**Issue by wyouflf** [cmake-js/cmake-js#300]
ERR! find VS
ERR! find VS msvs_version was set from command line or npm config
ERR! find VS - looking for Visual Studio version 2022
ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
ERR! find VS checking VS2022 (17.4.33213.308) found at:
ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
ERR! find VS - found "Visual Studio C++ core features"
ERR! find VS - found VC++ toolset: v143
ERR! find VS - missing any Windows SDK
ERR! find VS could not find a version of Visual Studio 2017 or newer to use
ERR! find VS looking for Visual Studio 2015
ERR! find VS - not found
ERR! find VS
ERR! find VS valid versions for msvs_version:
ERR! find VS
ERR! find VS **************************************************************
ERR! find VS You need to install the latest version of Visual Studio
ERR! find VS including the "Desktop development with C++" workload.
ERR! find VS For more information consult the documentation at:
ERR! find VS https://github.com/nodejs/node-gyp#on-windows
ERR! find VS **************************************************************
ERR! find VS
ERR! OMG Could not find any Visual Studio installation to use
ERR! OMG Could not find any Visual Studio installation to use
error Command failed with exit code 1.

**Comment by Julusian** [comment]
what version of cmake-js?

**Comment by wyouflf** [comment]
cmake-js:7.1.1

I found the new version https://github.com/nodejs/node-gyp/blob/main/lib/find-visualstudio.js that has updated, and it's support win11sdk.

**Comment by wyouflf** [comment]
> cmake-js:7.1.1
> 
> I found the new version https://github.com/nodejs/node-gyp/blob/main/lib/find-visualstudio.js that support win11sdk.

**Comment by wyouflf** [comment]
vs also has cmake buildin C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe

**Comment by Julusian** [comment]
please try v7.2.1

**Comment by wyouflf** [comment]
> please try v7.2.1

nice, it's works well

**Comment by Julusian** [comment]
glad to hear
Ill look into your suggestion of using the vs bundled cmake, but in its own task at another time https://github.com/cmake-js/cmake-js/issues/301
