### ISSUE TITLE
CMake-js run-time environment update checks (feature request)

### ISSUE THREAD

**Issue by bfrancojr** [cmake-js/cmake-js#31]
Hi,

Would be possible to turn off via CLI option the runtime environment update check that cmake-js does for every build?
It would make builds faster and be helpful for situations when there no connectivity.

Thanks!

**Comment by unbornchikken** [comment]
Do you mean the check of the availability of runtime's headers and libraries? Buy without them the build will fail for sure, so that is a mandatory process.

**Comment by bfrancojr** [comment]
Correct me if I am wrong, but I believe the dependency check could look at the local file system first for then, download all required packages from the internet if something is missing.

**Comment by unbornchikken** [comment]
That should behave that way you've described. Maybe you've found a bug, haven't you?

Look, the flow is the following:

https://github.com/unbornchikken/cmake-js/blob/master/lib/es6/buildSystem.js#L32
https://github.com/unbornchikken/cmake-js/blob/master/lib/es6/dist.js#L89
https://github.com/unbornchikken/cmake-js/blob/master/lib/es6/dist.js#L46

So basically it's intended to check the file system first, then invokes the download if something is missing.

**Comment by bfrancojr** [comment]
Hey,

I double checked this issue out and cmake-js is somehow working properly now.
Since then, we've upgraded our native module to make use of the latest nodejs runtime. Maybe that's why?

Thanks!

**Comment by unbornchikken** [comment]
In old and new exactly what runtime versions do you mean?
