### ISSUE TITLE
Failing to resolve node_api.h with Microsoft intellisense in Visual Studio Code

### ISSUE THREAD

**Issue by GeorgeBarlow** [cmake-js/cmake-js#321]
I know this is most definitely a user error but wanted someone to help spot my wrongdoings so I can therefore resolve my issues when using cmake-js, vscode and Microsoft C++ intellisense. 

```cmake
set_target_properties(demo  PROPERTIES
      PREFIX ""
      SUFFIX ".node"
    )

  execute_process(COMMAND node -p "require('node-addon-api').include"
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE NODE_ADDON_API_DIR
  )
  string(REGEX REPLACE "[\r\n\"]" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
  message(STATUS "Found node-addon-api at ${NODE_ADDON_API_DIR}")
  if (UNIX)
    target_include_directories(demo  PRIVATE "/usr/include/node") # node_api.h, need to find a way to avoid hardcoding this
  endif()
  if (WIN32)
    target_include_directories(demo PRIVATE "$ENV{USERPROFILE}/.cmake-js/node-x64/v18.17.1/include/node")
  endif()

  target_include_directories(demo  PRIVATE ${NODE_ADDON_API_DIR})
  ```
  
  This is my CMakeLists.txt and how I've got vscode's intellisense to work and find the `node_api.h` file. This is by explicitly including the correct path in `target_include_directories`. On Windows, as you can see it is within the `.cmake-js` directory on macOS it seems mine resides in `/usr/include/node`. I've tried to follow the installation guides and best practices when using cmake-js but this feels wrong, explicitly defining the target include directory to where `node_api.h` resides. I've tried not doing this and putting it within the `C/C++ Configurations -> Include path`  string array within vscode specifying the same `C:/Users/{username}/.cmake-js/node-x64/v18.17.1/include/node` directory and yet it still fails and acts as if it can't resolve `node_api.h`.
  
  I want to stress I understand this is most definitely a user error where I've either done something wrong or whatnot, but I just wondered if someone could help point out what exactly I'm doing wrong or what not. My current vscode setup is set to `No active kit` on cmake tools and I configure everything as normal with the `cmake-js configure` command and build it with the respective commands and the actual building and configuring works perfectly. The issue is only regarding the intellisense on vscode can't find `node_api.h`.
  
  Thanks all :)

**Comment by nathanjhood** [comment]
Hello George,

I'm not involved with the development of cmake-js but have been using quite a bit recently, to make modules in a similar fashion to your description. I can see the issue you are having and thought maybe I could offer some help.

The distinction between NodeJS's API's is a bit tricky at first, and takes a moment to fully understand. You essentially have two API's; one is NodeJS actual API, which is written in C, and makes use of several other libraries (v8, libuv, etc) all at once, with really strict version dependencies; these files ship in the location of your system NodeJS installation, such as ```/usr/include/node``` and in Windows' 'program files' installation directories (I think?). When cmake-js installs itself on your system globally, you will also find these files at ```{HOME}/.cmake-js/...``` as you can see above.

All of the above is seperate to the Node Addon API written in C++, which nicely wraps all of the other underlying libraries  and version dependencies into a C++ library. 

It looks to me like you are trying to access the C++ API, the Node Addon API.

Some things I suggest you do;

- add the packages ```node-addon-api``` *and* ```node-api-headers``` to your NodeJS project dependencies
- check your project's ```node_modules``` directory to find both of the above directories - all of the headers your intellisense engine needs are in there
- add those paths to your IDE's intellisense engine

You can link with both of those packages by taking this part of your ```CMakeLists.txt```:

```.cmake
  execute_process(COMMAND node -p "require('node-addon-api').include"
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE NODE_ADDON_API_DIR
  )
```

and replicating it for the other package:

```.cmake
# Include Node-API headers
execute_process(
  COMMAND node -p "require('node-api-headers').include_dir"
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE NODE_API_HEADERS_DIR
)
# Include Node-API wrappers
execute_process(
  COMMAND node -p "require('node-addon-api').include"
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE NODE_ADDON_API_DIR
)
```

Some of my implementations are overall very similar to the approach that I think you are looking for here. May I suggest you take a look at these two Node Addon projects of mine for further ideas:

- [base64](https://github.com/nathanjhood/base64)
- [noderc](https://github.com/nathanjhood/noderc)

Your questions suggest that you're pretty close already, but maybe these examples will help clear up any further questions you have there - please check the README, CMake modules in ```share```, and ```CMakeLists.txt``` for some detail.

Thanks and good luck! 

Nathan

**Comment by GeorgeBarlow** [comment]
Hi Nathan,

Thank you so much, I can't believe I overlooked that. We use `vcpkg` already and I found a port that included the headers, tried it out and everything now seems to work fine!

Thank you :)
