### ISSUE TITLE
missing header v8-callbacks.h included from v8-isolate.h

### ISSUE THREAD

**Issue by d3x0r** [cmake-js/cmake-js#333]
`~/.cmake-js/node-x64/v22.3.0/include/node/v8-isolate.h` which is somehow included from v8.h... should be nothing special...

My question is who maintains the headers you download?  Where do they come from?

v8-callbacks.h is not in that directory for v22.3.

**Comment by Julusian** [comment]
We download them from nodejs.org. in this cae it would be the url https://nodejs.org/dist/v22.3.0/node-v22.3.0-headers.tar.gz
Interestingly it looks like the file you are missing is in that archive

**Comment by d3x0r** [comment]
strange - installed on a different system and had no issues... wonder how files get randomly dropped... I suppose if I clear out the cache and redownload it would work.
