### ISSUE TITLE
Linking .dylib libraries for addon

### ISSUE THREAD

**Issue by gerhardberger** [cmake-js/cmake-js#34]
Hi!

I'm writing an addon that needs several `.dylib` libraries. On OSX after building them, I copy them to `/usr/local/lib`. In my `CMakeLists.txt` I write:
``` cmake
target_link_libraries(
  ${PROJECT_NAME}
  ${CMAKE_JS_LIB}
  /usr/local/lib/libExample.dylib
)
```
 And after compiling the addon with `cmake-js` it runs correctly.
However if I don't copy it into `/usr/local/lib` and specify its original path in `CMakeLists.txt`, it doesn't work. It compiles, but at runtime it stops.

How should I link it correctly?

Thanks

**Comment by RSATom** [comment]
run `otool -L your.node` and you will see where it tries load .dylibs

**Comment by gerhardberger** [comment]
Thanks for the answer!

With `otool -L my.node` i see that it tries to locate it at `@rpath/libExample.dylib`. But I don't know what's the value of `@rpath`. I tried to print it with: `otool -l my.node`, but I don't get the `LC_RPATH` command where it should be.
I also tried to set it with: `install_name_tool -id libExample.dylib path/to/libExample.dylib`, but it doesn't recognize it this way neither.

**Comment by RSATom** [comment]
https://wincent.com/wiki/@executable_path,_@load_path_and_@rpath

I think it expects `libExample.dylib` near the `your.node`

**Comment by gerhardberger** [comment]
Yeah, I tried that earlier too, but still get:
```
ld: library not found for -l@rpath/libExample.dylib
```

**Comment by RSATom** [comment]
http://qin.laya.com/tech_coding_help/dylib_linking.html

try use `@loader_path/libExample.dylib`

**Comment by gerhardberger** [comment]
And how should I set `@loader_path` in this case? Also I just realized that placing something next to the `.node` has no effect, because when I start building the `build` folder is cleared.

I tried to set `@rpath` in CMake described in [this link](https://cmake.org/Wiki/CMake_RPATH_handling), but didn't have much luck.

**Comment by RSATom** [comment]
with  `install_name_tool`, but it's possible it will not work for you since `@loader_path/libExample.dylib` just longer than `@rpath/libExample.dylib` and it will be not enough space for it...

it seems you will have to understand how to do 
> the down side: you now have to pass additional linker flags when building the host application (eg. -rpath @executable_path/../Frameworks or /Library/Frameworks; note that specifying both will cause the dynamic linker to try looking in both locations)

( it's from https://wincent.com/wiki/@executable_path,_@load_path_and_@rpath )

maybe https://cmake.org/Wiki/CMake_RPATH_handling really could help, don't sure yet

**Comment by unbornchikken** [comment]
This is a CMake related question. I suggest to try its mailing list to get a proper help.
