### ISSUE TITLE
How to integrate with a regular CMake based project?

### ISSUE THREAD

**Issue by KrishnaPG** [cmake-js/cmake-js#35]
Is some special procedure required to add the cmake-js based project as part of a regular cmake based builds?

I have CMake based project that generates a cpp static library, which is the root project.

I am trying to add the `cmake-js` addon project as a sub-directory that depends on the root static cpp library.

The `cmake-js build` command is working fine from command prompt. But, when invoking through the parent project with  `ADD_SUBDIRECTORY(...)` it is not generating the correct js includes / libs, resulting in compiler errors.

Printing the `${CMAKE_JS_LIB}` value is giving empty values when building as part of the regular CMake projects.

Question:
````
How to integrate the cmake-js sub-project to be part of the bigger regular CMake project correctly?
````

**Comment by Zikoel** [comment]
Hi, you have close the issue without a solution! Can you explain how you have solved? I am in the same situation! Thanks.

**Comment by KrishnaPG** [comment]
I gave up on that and used `npm install` rather, with below package.json configuration:
````
  "dependencies": {
    "node-cmake": "^1.1.0",
  },
  "devDependencies": {},
  "scripts": {
    "install": "ncmake --config MinSizeRel --build build"
  }
````
This `ncmake` takes care of doing the right thing.

**Comment by unbornchikken** [comment]
@KrishnaPG  What the fuck is node-cmake? :)

@Zikoel if you have an issue with **CMake.js**, do not hesitate to open up another thread there, I'll do my best to help you out.
