### ISSUE TITLE
Gyp to cmake tool

### ISSUE THREAD

**Issue by m1sta** [cmake-js/cmake-js#36]
Do you know of anyone working on a tool to automate the process of transitioning from node-gyp to cmake.js?

**Comment by RSATom** [comment]
Don't think so. Why do you need it?

**Comment by m1sta** [comment]
I'd love to see a rapid transition from node-gyp to cmake.js. Installing python to use node drives me insane. I'm thinking that a tool to make it easy for people to transition a package from one build system to  another would make this faster.

**Comment by m1sta** [comment]
I'd most like to see some method so that the consumer of the packages could choose the build system, ie. a particular node.js project could choose to cmake.js for building all of the native addons it's using. I suspect this is an impossible dream though.

**Comment by unbornchikken** [comment]
Unfortunately that's not possible because of the fundamental differences of CMake and GYP build systems.
