### ISSUE TITLE
v3.1 broken

### ISSUE THREAD

**Issue by mashiya** [cmake-js/cmake-js#40]
I am getting the following after installing the new version (Both on OSx and Ubuntu):

```
$ cmake-js
: No such file or directory
```

reverting back to v3.0 fixes the problem which suggests that the new version is broken.

**Comment by unbornchikken** [comment]
Ahh, the latest publish accidentally made cmake-js binary to use Windows style line endings that broke Linux mode executable. Please try HF 3.1.1.

**Comment by mashiya** [comment]
I thought so. It's fixed now! Thanks.
