### ISSUE TITLE
suggestion: add a pointer on using a heroku buildpack to include cmake

### ISSUE THREAD

**Issue by mrose17** [cmake-js/cmake-js#43]
perhaps this is documented somewhere that i couldn't find... but it'd be helpful for the folks that use heroku to know how to get cmake into the build system, e.g.,

        heroku buildpacks:set https://github.com/ddollar/heroku-buildpack-multi.git --app $APP

then create .buildpacks with these two lines:

        https://github.com/brave/heroku-cmake-buildpack.git
        https://github.com/heroku/heroku-buildpack-nodejs.git

**Comment by unbornchikken** [comment]
Since I dunno Heroku, I'd appreciate a PR for this.

**Comment by mrose17** [comment]
a reasonable request. please stand by!

**Comment by mrose17** [comment]
enjoy!
