### ISSUE TITLE
[Enhancement] Defining a special CMake variable to indicate that CMake.js is being used

### ISSUE THREAD

**Issue by maddouri** [cmake-js/cmake-js#48]
Hello,

I would like to suggest adding a new CMake variable (e.g. `NPM_CMAKEJS`) to the set of variables defined by CMake.js when configuring the project. (i.e. something like `D.push({"NPM_CMAKEJS": "TRUE"});` in `cMake.js`)

This would indicate that CMake has been invoked by CMake.js. (as opposed to a call from the command line or by an IDE such as CLion)

Having such a variable allows more flexibility in the `CMakeLists.txt`. For instance, when working on a complex project, it can be used to switch between sub-projects:

```cmake
if (NPM_CMAKEJS)
    add_subdirectory(node_addon)
else()
    add_subdirectory(other_subproject)
endif()
```

Thanks :)

**Comment by unbornchikken** [comment]
https://github.com/cmake-js/cmake-js#cmake-specific
