### ISSUE TITLE
"There is no Visual C++ compiler installed. Install Visual C++ Build Toolset or Visual Studio"

### ISSUE THREAD

**Issue by davidmurdoch** [cmake-js/cmake-js#49]
I'm receiving this error when running `cmake-js compile` on Windows 10 with Visual Studio 2015 Community installed. I have all the  Visual Studio Visual C++ tools installed, and even restarted for good measure, yet the error remains.

I also tried adding `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Bin\` to my PATH and even tried to run it as Administrator but that doesn't work either.

Any ideas as to what could be going wrong?

**Comment by maddouri** [comment]
I have a similar environment. (Win10x64 + MSVC 2015 Community) CMake was able to find MSVC.

Are you able to compile a simple C++ program with Visual Studio ? If not, you might be facing a similar problem to the one discussed in this [SO thread](https://stackoverflow.com/q/31619296/865719).

Finally you might get lucky if you use the "Developer Command Prompt for VS2015" (don't forget to add Node.js and CMake paths when you use it)

**Comment by unbornchikken** [comment]
I cannot reproduce this either. Which version of CMake are we talking about?

**Comment by davidmurdoch** [comment]
I'm not sure, this computer is only a few weeks old... but unfortunately it booted to a BSOD today and it doesn't look like it'll recover with my data in-tact ... so I can't test. Once I get it up and running again i'll give this another shot.

**Comment by grrrwaaa** [comment]
Having a similar issue here, discovered trying to npm install fastcall
https://github.com/cmake-js/fastcall/issues/26
