### ISSUE TITLE
Problem with line endings on Ubuntu and OSX in version 3.2.2

### ISSUE THREAD

**Issue by cciliber** [cmake-js/cmake-js#51]
Hi, I noticed that in the last version of cmake-js (version 3.2.2 to this date) there is some problem with line endings. Specifically if I npm install this version and then try to run cmake-js I get
```
$> cmake-js 
: No such file or directory
```
on Linux (both Ubuntu 12.04 and 14.04), and 
```
$> cmake-js
env: node\r: No such file or directory
```
on OSX (El Capitan)

I found a hint that this could be due to line endings thanks to [this StackOverflow post]((http://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo)  and indeed by following the suggested procedure I was able to locally fix the cmake-js script. 

Would it be possible to correct this in the Cmake.js project itself?

BTW, thanks for the great project : )

**Comment by unbornchikken** [comment]
Interesting, since the binary file hasn't changed since 3.2.0. I'm gonna try latest later today because I have no Linux on reach right now.

**Comment by unbornchikken** [comment]
@cciliber Could you try 3.2.3 on Linux or OSX?

**Comment by cciliber** [comment]
Tested on OSX and it works flawlessly! Thanks!

**Comment by unbornchikken** [comment]
Just for the record, it was Visual Studio Code that tricked me this time.
