### ISSUE TITLE
cmake-js uses old headers

### ISSUE THREAD

**Issue by d3x0r** [cmake-js/cmake-js#56]
the current node version is 6.5.0
the headers it's including is ~/.cmake-js/node-x64/v6.3.1/include/node

There's no env.h Header?

**Comment by unbornchikken** [comment]
I bet CMake has already been configured to a previous version of node. It remembers its parameters. You can delete node_modules and reinstall everything, or delete the given CMake.js based module then reinstall it, or do a `cmake-js rebuild` in its directory.

**Comment by unbornchikken** [comment]
I'm closing this. Do not hesitate to reopen if the issue arise again.
