### ISSUE TITLE
Is there a way to set the CMake Generator instead of detect?

### ISSUE THREAD

**Issue by rogeriorc** [cmake-js/cmake-js#63]
I need to build with a especified vs version (-G"Visual Studio 11 Win64") , but the machine also contains VS 2015. There are any option to force the generator?

**Comment by unbornchikken** [comment]
Unfortunately that's not supported right now. I'm planning to add support for custom generators on the next major version. However if you happen to have a PR it would be welcome of course.

**Comment by d3x0r** [comment]
https://github.com/cmake-js/cmake-js/pull/64
