### ISSUE TITLE
Appveyor and Travis based support for automatic distribution of binary releases hosted on Github

### ISSUE THREAD

**Issue by unbornchikken** [cmake-js/cmake-js#70]
As title says. Kinda integrated [node-pre-gyp-github](https://www.npmjs.com/package/node-pre-gyp-github).

You can vote up this issue by a regular +1 or with a small amount of [![](https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=LMERWE2EHYC2E&lc=HU&item_name=Vote%20up%20CMake%2ejs%2370&item_number=CMake%2ejs%2370&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by tiangolo** [comment]
You might want to check [prebuild](https://github.com/mafintosh/prebuild) too.

It is used, for example, by [zeromq.js](https://github.com/zeromq/zeromq.js).

**Comment by tiangolo** [comment]
I started a stub with Travis for Linux, but I'm getting an error:

https://travis-ci.org/tiangolo/cmake-js/jobs/230024428#L844

`cc1plus: error: unrecognized command line option ‘-std=c++11’`

**Comment by Julusian** [comment]
I don't think this is worth doing as part of this project.
prebuild & prebuild-install work fine with cmake-js
