### ISSUE TITLE
Multiple toolchains

### ISSUE THREAD

**Issue by jugglingcats** [cmake-js/cmake-js#73]
Hi am new to CMake in general and cmake-js, so excuse me if this is a basic question.

I'd like to set up cmake-js to compile my node addon for multiple target platforms:
- Linux x64
- Linux ARM
- i386
- Windows x64

I am looking at getting the mingw toolchain set up on Linux ready to cross compile.

Any advice / links on configuring cmake-js / CMakeLists.txt to output all targets at once, or command line options to control desired output?

In the readme it says: "Notice: on non-Windows systems the C++ toolset's architecture's gonna be used despite of this setting". Does this mean we need to re-configure the default toolchain before running cmake-js.

Thanks

**Comment by unbornchikken** [comment]
You don't have to do anything special for multiple system and node runtime support. Please do the first tutorial.
