### ISSUE TITLE
Module parse error in electron app

### ISSUE THREAD

**Issue by davidbernstein** [cmake-js/cmake-js#74]
Sorry if this is the wrong place to ask but I need some help getting a cmake-js module working in an electron app. I followed the tutorials and electron related sections. My module installs and builds correctly but when I try to require it in the app I get an error starting with

ERROR in ./~/coily/build/Release/coily.node
         Module parse failed: /Users/Dave/Repositories/QUDA/QBert/ugg/node_modules/coily/build/Release/coily.node Unexpected character '�' (1:0)
         You may need an appropriate loader to handle this file type.
         SyntaxError: Unexpected character '�' (1:0)

I'm on OS X and in the app's top level package.json file I have this section:
"cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "1.4.14",
    "arch": "x64"
  },

The require line is
var coily = require('coily/build/Release/coily.node')

Any advice would be greatly appreciated!

**Comment by davidbernstein** [comment]
My bad, I forgot some NAN and NODE_MODULE functions in C++ code. It is all working now. Can I suggest that in the Electron part of the cmake-js description that a line about the render v.s. main process be added?

**Comment by unbornchikken** [comment]
I'm not an expert of Electron. Would you please lend me a hand, an make a PR of this line?

**Comment by davidbernstein** [comment]
Sure, I modified the README and opened a PR for it.
