### ISSUE TITLE
ABI compatibility problems

### ISSUE THREAD

**Issue by heapwolf** [cmake-js/cmake-js#76]
When I build my native module for electron (using -r to specify the electron runtime, for which i have the latest version installed), I get an error similar to this...

```
...The module `x` was compiled against a different Node.js version using NODE_MODULE_VERSION 50 This version of Node.js requires NODE_MODULE_VERSION 51...
```

However, I have node.js latest version installed who's [ABI version is 51](https://nodejs.org/en/download/releases/).

Could it be that cmake-js is not using the correct nodejs headers to build?

**Comment by 0x00A** [comment]
Just to follow up, i was able to fix this by installing electron as a local dependency.

**Comment by cjamin** [comment]
I had the problem, and could only solve it using 0x00A's solution. Any explanation? Thanks!

**Comment by Julusian** [comment]
I expect this was either a mistake in the node-abi library causing cmake-js to build it wrong, or it wasnt being invoked correctly.
As this is for an EOL electron, I expect this to no longer be a problem
