### ISSUE TITLE
'npm config set cmake_...' is not set in configure

### ISSUE THREAD

**Issue by Xaymar** [cmake-js/cmake-js#79]
I have a CMakeLists.txt that depends on other CMake based projects (that aren't based on node.js), so I need to be able to configure proper paths to them. However, cmake-js just ignores what I give it and either trashes the CMake cache or just forgets to set it. The following commands:

```
npm config set cmake_MyVariable TEST --global
npm config set cmake_MyVariable2 HELLOWORLD
cmake-js configure
```

Will result in:

```
MyVariable is: 
MyVariable2 is: 
```

Is there a fix planned?

**Comment by Xaymar** [comment]
The reason for this seems to be that cmake-js converts the name to uppercase, so MyVariable ends up being MYVARIABLE.

**Comment by unbornchikken** [comment]
Yeah. It gets converted to "-D<varname>", and by convention `varname` is uppercase. It's not stated explicitly in the readme, but it should be obvious according to the provided [example](https://github.com/cmake-js/cmake-js#example).
