### ISSUE TITLE
Platform Headers Missing

### ISSUE THREAD

**Issue by d3x0r** [cmake-js/cmake-js#80]
C:\Users\d3x0r\.cmake-js\node-x64\v7.7.2\include\node\openssl\ 
this is missing ssl.h and tls.h at least.

Are these packages built by you or downloaded from node somewhere?

**Comment by unbornchikken** [comment]
Downloaded. It's the official header package. Maybe they has changed something in the SDK ... again. I'll look into it as soon as I have some spare time.

**Comment by d3x0r** [comment]
I implemented the build with node-gyp and it didn't have a problem with ssh.h and tls.h in openssl in node headers....

**Comment by unbornchikken** [comment]
Which means that something has changed in the SDK packages for 7.x+ the I should follow.

**Comment by d3x0r** [comment]
This hasn't been an issue for quite some time.
