### ISSUE TITLE
Update Readme?

### ISSUE THREAD

**Issue by 0x00A** [cmake-js/cmake-js#81]
Is [this](https://github.com/cmake-js/cmake-js#note) note about electron only relevant to the `1.4.x` branch or relevant to everything greater than or equal to `1.4.x`?

**Comment by unbornchikken** [comment]
1.4.x+

**Comment by 0x00A** [comment]
Huh. Well, im calling [`this`](https://github.com/voltraco/node-taglib2) module from the render thread and it works fine (just not on macOS `<= 10.10.5`).
