### ISSUE TITLE
Building cross-platform NW.js applications

### ISSUE THREAD

**Issue by matthew-dean** [cmake-js/cmake-js#82]
One thing that's not clear from the documentation - if you're building NW.js applications, does CMake.js have to execute (build) on every platform that you're building an NW.js app for? If so, can you provide some documentation for that? If not, can you state something explicitly to that effect?

**Comment by unbornchikken** [comment]
Yes, you should build your app for every platform. There is a documentation for that already (https://github.com/cmake-js/cmake-js#runtimes)[over there].

So, basically, you put tour app's package.json the following:

```json
"cmake-js": {
    "runtime": "nw.js",
    "runtimeVersion": "x.y.z"
  }
```

Then the following command will build you app on each platform without any platform specific arguments:

```bash
cmake-js compile
```

Or if you have the following script defined in package.json:

```json
"scripts": {
    "install": "cmake-js compile"
  }
```

then

```
npm install
```

will build you app on each possible platforms.

**Comment by matthew-dean** [comment]
> Yes, you should build your app for every platform

That's not my question. Do you have to physically run cmake-js **ON** every platform. That is, do you need to run it on a Windows machine for a Windows build, then a Mac for a Mac build, and then a Linux machine for a Linux build. So do you need 3 computers (or virtual machines) to run cmake-js?

**Comment by nhz-io** [comment]
@matthew-dean You have to run it on every target OS. This is not cmake-js limitation.
This is node limitation. You cannot cross-compile native modules with mingw - no chance to link against **node.lib** - wasted lots of sleep on this

**Comment by unbornchikken** [comment]
@nhz-io answered this correctly. Thanks.
