### ISSUE TITLE
electron-builder: how to set a dependency's cmake-js' arch without using package.json

### ISSUE THREAD

**Issue by tiangolo** [cmake-js/cmake-js#83]
## General description

I'm building an Electron app with [electron-builder](https://github.com/electron-userland/electron-builder).

I'm using a dependency package that uses `fastcall` (`cmake-js`)... I actually wrote the part that uses `fastcall` in that dependency package.

I can use the instructions in https://github.com/cmake-js/cmake-js#electron and add to `package.json`:

```json
...
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "1.6.7",
    "arch": "x64"
  }
...
```

And when I run `npm install` it downloads and builds the dependency package as expected.

Then I can execute electron-builer's `build` command with an arch `x64`, as in: `build --x64`.

Up until then, it all works perfectly.

## The problem

But electron-builder supports creating an installer that targets `x64` and `ia32`. What it does is rebuild all the packages for each arch, for that, it uses [electron-gyp](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/yarn.ts#L35) and family. And after it builds and creates both versions of the app it put's both of them in a single `.exe` file.

So, I need a way to change the target architecture "on the fly", not in the package.json.

Also, if I try running `cmake-js rebuild --runtime=electron --arch=ia32` that tries to build the current project / package, that doesn't depend on `cmake-js` / `fastcall`. What I need to rebuild with a different architecture is a dependency package.

Is there any command, environment variable or any way to "rebuild dependencies" that doesn't involve modifying the `package.json`?

I see there is [`NODE_ARCH`](https://github.com/cmake-js/cmake-js#runtime-options-in-cmakeliststxt) as a variable for `CMakeLists.txt`, but not as an environment variable.

I'm thinking that maybe with that I can use [electron-builder's programatic API `beforeBuild` callback](https://github.com/electron-userland/electron-builder/wiki/Options#config--platformspecificbuildoptions). It would be quite more complex than what I would like, but at least would be something.

## Summary

My main problem is, how can I use a `cmake-js` dependency and make `electron-builder` build both architectures without having to modify the `package.json`?

But I know that can be quite specific to my use case. So, a first approximation would be, how can I, programmatically (with environment variables, parameters or something) rebuild my dependency packages that use `cmake-js` targeting a specific architecture?

---

Is there anything else I'm missing? I searched in all the documentation, tutorials and issues I found in this project, but didn't really find an answer.

**Comment by unbornchikken** [comment]
Try this at home:

```bash
npm config set cmake_node_runtime="node|iojs|nw|electron"
npm config set cmake_node_runtimeversion="x.y.z"
npm config set cmake_node_arch="x64|ia32|arm"
```

How this works?

You can set CMAKE options vit npm config: https://github.com/cmake-js/cmake-js#custom-cmake-options

And there are special ones that CMake.js will understand: https://github.com/cmake-js/cmake-js#runtime-options-in-cmakeliststxt

Hope it helps.

**Comment by tiangolo** [comment]
As I needed to support Windows 32 bits for this, the main issue / feature request would be: https://github.com/cmake-js/fastcall/issues/17

For my specific problem I ended up using `node-ffi`, so I won't be able to test this more, I'm sorry.

I will then just close this issue, to reduce the noise in the repo.
