### ISSUE TITLE
Building N-API module with node-addon-api

### ISSUE THREAD

**Issue by ealib** [cmake-js/cmake-js#84]
I tried building a native module that uses only [N-API](https://github.com/nodejs/abi-stable-node) calls (imported from [Node.js v8.0.0-rc.1](https://nodejs.org/download/rc/v8.0.0-rc.1/)).

It worked if I `#include <node_api.h>`'ed, instead of `napi.h`, which is at the moment available from [node-addon-api](https://github.com/nodejs/node-addon-api) only.

To build successfully with `node-addon-api` installed via

    npm install node-addon-api

I had of course to add

```cmake
# Include N-API wrappers
target_include_directories(${PROJECT_NAME} PRIVATE "${CMAKE_SOURCE_DIR}/node_modules/node-addon-api")
```

**Comment by unbornchikken** [comment]
As I see not it should be a section in the readme instead of a bug that needs to be fixed, right? Maybe you could make a small PR for the readme of the above?

**Comment by ealib** [comment]
PR done.

**Comment by Tzelon** [comment]
I tried to use this but I get the following error:
 Cannot find source file:
    node_modules/node-addon-api/node_api.h

**Comment by pirxpilot** [comment]
To clarify: when you say _when I run cmake_, do you mean _when I run cmake-js_?
I am not saying that there isn't an issue somewhere here. I am only asking because this is sort of the error behavior I would expect if one accidentally runs `cmake` and not `cmake-js`.

To check if `cmake-js` properly locates node includes run:

    cmake-js print-configure

And look for `-DCMAKE_JS_INC=` setting. Check if `node_api.h` is in that directory. If not try.

    cmake-js install

**Comment by Tzelon** [comment]
@pirxpilot Thanks, silly me... I ran cmake and not cmake-js

**Comment by marcus-sa** [comment]
I got the same issue currently.
Seems like your documentation is outdated at https://github.com/cmake-js/cmake-js#n-api-and-node-addon-api

Check my issue ticket in https://github.com/venobo/cerberus/issues/1 for more details.

**Comment by Julusian** [comment]
It sounds like this is an issue with include paths not being setup correctly. This is documented in the readme on npm (not on github), and will be unnecessary in 7.0.0
