### ISSUE TITLE
v8::JSON::Parse compile error in `npm test` suite

### ISSUE THREAD

**Issue by p-jackson** [cmake-js/cmake-js#88]
In a clean working directory these tests fail:
- `BuildSystem Build with various options should build with: { runtime: 'nw', runtimeVersion: '0.12.3', arch: 'x64' }`
- `BuildSystem Build with various options should build with: { runtime: 'nw', runtimeVersion: '0.12.3', arch: 'ia32' }`

They both have this compile error
```
cmake-js\node_modules\nan\nan_json.h(89): error C2660: 'v8::JSON::Parse': function does not take 2 arguments
```

I'm on Windows 10, CMake version is 3.7.1 and have VS2012, VS2015 and VS2017 installed.

**Comment by p-jackson** [comment]
On my Mac there are two errors
```
~/.cmake-js/nw-x64/v0.12.3/deps/v8/include/v8.h:6359:54: error: 'CreateHandle' is a protected member of 'v8::HandleScope'
  return Handle<T>(reinterpret_cast<T*>(HandleScope::CreateHandle(
                                        ~~~~~~~~~~~~~^~~~~~~~~~~~
```

```
cmake-js/node_modules/nan/nan_json.h:89:50: error: too many arguments to function call, expected single argument 'json_string',
      have 2 arguments
    result = v8::JSON::Parse(context_or_isolate, json_string);
             ~~~~~~~~~~~~~~~                     ^~~~~~~~~~~
```

(it could be that both errors happen on Windows too but it just prints differently) 

And five of the unit tests are failing
- `{ runtime: 'nw', runtimeVersion: '0.12.3', arch: undefined, preferClang: true, referMake: true }`
- `{ runtime: 'nw', runtimeVersion: '0.12.3', arch: undefined, preferClang: true }`
- `{ runtime: 'nw', runtimeVersion: '0.12.3', arch: undefined, preferGnu: true, referMake: true }`
- `{ runtime: 'nw', runtimeVersion: '0.12.3', arch: undefined, preferGnu: true }`
- `{ runtime: 'nw', runtimeVersion: '0.12.3', arch: undefined }`

**Comment by Julusian** [comment]
As of the latest commit, the tests build cleanly in the latest node.
This old issue was likely due to running the tests against a newer version of node than they supported
