### ISSUE TITLE
Depending on a project that isn't in the addon folder

### ISSUE THREAD

**Issue by tom-seddon** [cmake-js/cmake-js#89]
I've got a Node addon that depends on another project.

Following a suggestion made in #6, I've got the dependency in a `deps` folder inside the addon's folder. So the folder structure is a bit like this:

    timer_addon\ [C++ Node addon built using cmake-js - package.json, CMakeLists.txt]
    timer_addon\deps\cpp_lib\ [non-Node C++ library - CMakeLists.txt]
    timer_app\ [Electron app]

The addon CMakeLists.txt refers to the cpp_lib CMakeLists.txt using `add_subdirectory`; the timer_app package.json refers to the timer_addon package using a `file:../timer_addon` dependency. And that all works. [You can see this code in the deps_folder branch of my test BitBucket repo](https://bitbucket.org/tom_seddon/js_addon_multi_test/src/2ec9c1b37e9d3b6a78649f20a9b0330ae2e59cc2?at=deps_folder).

But suppose I don't want the dependency folder structure as a child of the addon folder. The C++ library is consumed by more than just the Node addon, so I'd prefer a folder structure more like this:

    timer_addon\ [C++ Node addon built using cmake-js - package.json, CMakeLists.txt]
    cpp_lib\ [non-Node C++ library - CMakeLists.txt]
    timer_app\ [Electron app]

But when I try doing this - and you can see my attempt [in the no_deps_folder branch of my test BitBucket repo](https://bitbucket.org/tom_seddon/js_addon_multi_test/src/3f26f1e7ebed7ce28b356537549b271678aa4d51?at=no_deps_folder) - it seems that running `npm install` in the app folder copies the folder structure for the addon, but not the folder structure for the project it depends on, with predictable results:

    CMake Error at CMakeLists.txt:4 (add_subdirectory):
      add_subdirectory given source "../cpp_lib" which is not an existing
      directory.

Is this supported? Is there anything I can do to make it work this way?

Thanks,

--Tom

**Comment by Julusian** [comment]
I think this is more of a problem with the node path resolution process. 
By using `file:../timer_addon` you are telling npm/yarn to copy the `timed_addon` into the node_modules folder. Which means your definition in cmake will not be correct.
There isnt anthing cmake-js can do here, as it doesnt know that it was copied from somewhere else on your computer.

If you are using yarn, you might have better luck with `link:../timer_addon`, but I am unsure on that. Or perhaps you can help out cmake by passing in an absolute path to the library through a variable.
