### ISSUE TITLE
Choose specific build targets instead of building all

### ISSUE THREAD

**Issue by dsamarin** [cmake-js/cmake-js#91]
We are using cmake-js to successfully create a node binding for a library we are developing, but the library itself only has a few dependencies. Running `cmake-js compile` successfully compiles everything but it also includes targets that we don't need for this build. In our case we only need the target for the binding which pulls in the proper dependencies.

Is it possible to specify a build target?

**Comment by unbornchikken** [comment]
It's currently not supported. We need an option to compile + build command to specify the target.

**Comment by simon-p-r** [comment]
I can try to do a PR for this if you want, I have an install target that is not being invoked by cmake-js.

**Comment by unbornchikken** [comment]
It would be geat.

**Comment by unbornchikken** [comment]
PR merged. Gotta test @master on Linux tomorrow before I make a release, because I tend to fuck up the main binary file when I make a commit on Windows regardless of git line ending settings.

**Comment by unbornchikken** [comment]
Released as of v3.6.
