### ISSUE TITLE
can cmake-js compile projects containing both c code and c++ code appropriately?

### ISSUE THREAD

**Issue by shtaif** [cmake-js/cmake-js#92]
* I'm relatively new with C/C++.

I'm trying to make myself a native c++ addon which depends on the [pigpio C Library](https://github.com/joan2937/pigpio) intended for a Raspberry Pi.

The compilation fails, emitting lots of errors about the main pigpio.c file (written in C code) regarding things like implicit type casting, using the `new` keyword as a variable name, and more...

Of course, theses errors show only when using `cmake-js compile` on my whole addon project (which is based on c++ as mentioned); as opposed, trying to compile the pigpio library alone with gcc directly and no c++ code involved - succeeds flawlessly.

Is there a way to tell cmake-js/cmake to treat `*.c` files as C code and compile them appropriately?
Or maybe I'm missing some point..?

**Comment by RSATom** [comment]
I'm pretty sure it's something wrong with your `CMakeLists.txt` file/files. Where did you get `CMakeLists.txt` file for pigpio?

**Comment by shtaif** [comment]
Thanks @RSATom, I just figured my last problem was caused because I wasn't including pigpio through it's header file `pigpio.h`.

This way, compilation seems to succeed, treating it as a proper C file.

However, trying to run the resulting addon encounters an error and crushes:

> symbol lookup error: /home/dor/projects/zvuv/imu-promise/build/Release/imu.node: undefined symbol: gpioInitialise

`gpioInitialise` is a function from pigpio which I call as soon as my addon is `require()`ed in the Node.js side.

Perhaps the functions from `pigpio` aren't linked correctly?


> Where did you get CMakeLists.txt file for pigpio?

Well, I did not, thinking that all I've got to do is add it's source code to my project... :(
Following is my only `CMakeLists.txt` file for this addon.
As can be seen, I'm cross-compiling from an Ubuntu PC (inside a VirtualBox) into a Raspberry Pi.

> cmake_minimum_required(VERSION 2.8)
> 
> \# Name of the project (will be the name of the plugin)
> project (imu)
> 
> \# Essential include files to build a node addon,
> \# you should add this line in every CMake.js based project.
> include_directories(${CMAKE_JS_INC})
> 
> \# Declare the location of the source files
> file(GLOB SOURCE_FILES "src/*.cc" "src/*.c" "src/*.h" "src/*.hpp")
> 
> 
> 
> set(CMAKE_SYSTEM_NAME Linux)
> set(CMAKE_SYSTEM_PROCESSOR arm)
> 
> set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
> set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c11")
> 
> set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
> set(CMAKE_CXX_STANDARD 14)
> 
> 
> 
> \# This line will tell CMake that we're building a shared library
> \# from the above source files
> \# named after the project's name
> add_library(${PROJECT_NAME} SHARED ${SOURCE_FILES})
> 
> \# This line will give our library file a .node extension without any "lib" prefix
> set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" SUFFIX ".node")
> 
> \# Essential library files to link to a node addon,
> \# you should add this line in every CMake.js based project.
> target_link_libraries(${PROJECT_NAME} ${CMAKE_JS_LIB})
>

**Comment by RSATom** [comment]
> Perhaps the functions from pigpio aren't linked correctly?

Yes

> Well, I did not, thinking that all I've got to do is add it's source code to my project... :(

It depends. Most libraries should be build by build scripts provided by lib authors.

**Comment by shtaif** [comment]
Well, as you suggested, the lib author does provide a build script in the pigpio website.
I was able to create a libpigpio.so file thanks to that, which I added to my project and to my cmake config:
`target_link_libraries(${PROJECT_NAME} ${CMAKE_JS_LIB} pigpio)`

I guess the best way should have been to set pigpio in my project with a nested CMakeLists.txt, but for now I'm happy because it works :)

Thanks!

**Comment by RSATom** [comment]
Glad to hear it. Then please close issue.
