### ISSUE TITLE
Additional options passed to CMake shouldn't be converted to upper case

### ISSUE THREAD

**Issue by skhrshin** [cmake-js/cmake-js#95]
* cmake-js version: 3.5.0

Since CMake variables are case-sensitive, some options like Boost_USE_STATIC_LIBS won't work as expected.

**Comment by smkanadl** [comment]
This is a really annoying bug. Is there any fix in progress?

**Comment by unbornchikken** [comment]
I'm really tight on schedule, so if anyone could write a clear bug report for this case, that would be really appreciated. Which feature is afftected with this? Passing custom cmake variables with "CD" argument?

**Comment by smkanadl** [comment]
Yes. If I pass `--CDlibmodbus_DIR:PATH=abc` to cmake-js it is transformed `-DLIBMODBUS_DIR:PATH=abc` for the CMake invocation. CMake variables are case-sensitive, so it is currently impossible to pass a lower-case variable to CMake using cmake-js.

**Comment by unbornchikken** [comment]
Well, thanks. That would be an easy semver patch fix. Expect it to land on today evening (UTC). Sorry for the delay. Things will move on faster if I get clear reports that points me to the right direction.

**Comment by smkanadl** [comment]
Sounds great, thank you very much!

**Comment by unbornchikken** [comment]
fixed as of 3.6.2
