### ISSUE TITLE
qt creator tutorial debug not building

### ISSUE THREAD

**Issue by corymickelson** [cmake-js/cmake-js#99]
whenever I try to debug in qt I get this error: 
This does not seem to be a "Debug" build.
Setting breakpoints by file name and line number may fail.

Section .debug_info: Not found.
Section .debug_abbrev: Not found.
Section .debug_line: Not found.
Section .debug_str: Not found.
Section .debug_loc: Not found.
Section .debug_range: Not found.
Section .gdb_index: Not found.
Section .note.gnu.build-id: Found.
Section .gnu.hash: Found.
Section .gnu_debuglink: Not found.

I've double and triple checked that I followed your instruction, but for one reason or another my Debug build doesnt work. Any idea's are more than welcome, I have no idea what else to try.

**Comment by unbornchikken** [comment]
Unfortunately (or fortunately) Qt Creator has been changing very frequently. Its CMake related features got a complete rewrite since I wrote that tutorial. I really tight on schedule, so don't expect a complete rewrite, but I'm gonna try to debug something with it and write a step-by-step instructions there.

**Comment by corymickelson** [comment]
I have been able to hit a break point in Qt but I the error message above is still shown, and I have to build the project outside of Qt with `cmake-js build -D`. Then in the Qt project I delete the build step, add the executable as node and the path to the .js file. At this point I can hit debug, and it shows the message, but stops at my breakpoints in my .cc file(s). I know this is not how it's meant to work, but if anyone else is having issues debugging in Qt this at least seems to work for me at the moment

**Comment by corymickelson** [comment]
I have been able to get this to work by adding a custom build step using cmake-js instead of cmake. My build step is: 
Command: ./node_modules/cmake-js/bin/cmake-js
Arguments: build -D
Working Directory: %{sourceDir}

**Comment by unbornchikken** [comment]
I consider it's done.
